### ISSUE TITLE
Inter-operators communication for Cross-Site configuration

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#1033]
This proposal describes how to make cross-site configuration easy and more secure. This is not about cross-site communication and transport layer definition.

## Current implementation
Currently, to create the cross-site configuration between several OKD/OCP/k8s clusters operator utilize remote connection to the Kubernetes API.
![image](https://user-images.githubusercontent.com/24249373/117548085-a0119d00-b03b-11eb-9ddd-2e8b24760a71.png)

Remote resources are configured for each Infinispan CR instance. The following resources are requesting on remote site which requires additional grants and permissions depends of the exposition types and provided cluster (OKD/OCP or different k8s deployments):
- Services (for LoadBanacer and NodePort exposition)
- Nodes (for NodePort exposition only)

## New implementation option
- Create a REST service inside the operator code and not exposed by default
- If need to setup cross-site, it's necessary to register all external operator instances inside operator configuration ConfigMap
- For cross-site configuration operator will call operator REST service on the foreign site to get required data (remote hosts and port of the cross-site service)

![image](https://user-images.githubusercontent.com/24249373/117548298-e4516d00-b03c-11eb-9d4b-8b8be48b99ef.png)

This solution will
- Reduce configuration complexity for more than one Infinispan cross-site configuration. Infinispan CR will contains just following `Url: operator://<cluster-mnemonic-name>` parameters. Access token to the remote service will be configured on the whole operator level
- Increase security. The operator level REST service token will contains access to the specific service with very limited list of the resources. Will not access to the Kubernetes API directly and cluster wide rights and roles. Also exposing Kubernetes API URL to the others OKD/k8s instances will not required. 

Also will be possible to have an option, where customer just configure Infinispan CR and operator will provision this CR to the other sites automatically create and configure cluster. This adds autopilot option to the operator for cross-site functionality.

**Comment by dmvolod** [comment]
@rigazilla , @ryanemerson and @pruivo any feedback will be appreciated

**Comment by dmvolod** [comment]
> I'm confused about the "operator level token". isn't it just to authenticate the operator? what kind of resources does it have access to?

Yes, sure. It's an operator REST service token of cause. Thanks.

**Comment by dmvolod** [comment]
> we probable can simplify the configuration of Infinispan CR even more. The operator can have a site name associated so the Infinispan CR would contain a list of URLs `operator://operator{1..N}`. The REST endpoint will return the site name, ip(s), port

Good point, thanks, it could be a good and more simple and compact configuration.
I still thinking about configuration Infinispan CR and propagation it to the other sites via operator REST service.

**Comment by pruivo** [comment]
+1 for the propagation

**Comment by ryanemerson** [comment]
I like the idea in general and I think just exposing a operator endpoint is more appealing than requiring the k8 cluster-wide roles.

A key consideration will be how we configure such an endpoint. What authentication mechanism do we use? How do we handle encryption etc.

> Also will be possible to have an option, where customer just configure Infinispan CR and operator will provision this CR to the other sites automatically create and configure cluster. This adds autopilot option to the operator for cross-site functionality.

This would be very cool :sunglasses: 

> * If need to setup cross-site, it's necessary to register all external operator instances inside operator configuration ConfigMap

Adding additional features like this, which may have multiple properties/files is why I preferred the idea of using a InfinispanConfiguration CR for global operator configuration instead of a ConfigMap. I guess we can see what the ConfigMap configuration would look like, but as we add more config options I think this will become error prone due to the lack of validation and schema for the user.

**Comment by dmvolod** [comment]
> A key consideration will be how we configure such an endpoint. What authentication mechanism do we use? How do we handle encryption etc.
> 

Very good  point. I think we could utilize the same mechanism as k8s implemented already, i.e. `BearerToken` and store it inside specific secret with the following structure
```
kind: Secret
apiVersion: v1
metadata:
  name: cross-site-lon-secret
  namespace: infinispan-operator
  annotations:
    infinispan.org/cross-site-secret: 'true'
data:
  clusterName: bG9u
  serviceLocation: YXBwcy5jbHVzdGVyLW1zay1jM2YzLm1zay1jM2YzLnNhbmRib3gxODY1Lm9wZW50bGMuY29t
  token: d3Fmd3Fmd3Fmd3FmcXc=
type: Opaque
```
We can store and easily exchange all data we need to another site with just one Secret and operator can automatically identify these secrets by annotations. 

> > Also will be possible to have an option, where customer just configure Infinispan CR and operator will provision this CR to the other sites automatically create and configure cluster. This adds autopilot option to the operator for cross-site functionality.
> 
> > * If need to setup cross-site, it's necessary to register all external operator instances inside operator configuration ConfigMap
> 
> Adding additional features like this, which may have multiple properties/files is why I preferred the idea of using a InfinispanConfiguration CR for global operator configuration instead of a ConfigMap. I guess we can see what the ConfigMap configuration would look like, but as we add more config options I think this will become error prone due to the lack of validation and schema for the user.

Yes, true. Having configuration CRD is very good idea and many others operators/controllers going away from the configurations   via ConfigMap. This will need additional code to implement but also very desirable feature and can be maintained easily.
