### ISSUE TITLE
Cross site clusterrolebinding for NodePort

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-operator#1038]
add following ClusterRoleBinding to each cross-site ServiceAccount 

```
oc create clusterrolebinding <name> -n ${NAMESPACE} --clusterrole=cluster-reader --serviceaccount=${NAMESPACE}:<account-name>
```

This is to use a nodeport URL with the `spec.service.sites.locations.url` field

**Comment by dmvolod** [comment]
Please also have a look at description inside the #1019 and discussion inside the #1035. This is a bit related problem how to detect and identify correct expose type for the platform.

**Comment by dmvolod** [comment]
Actual command for OCP/OKD is
`oc adm policy add-cluster-role-to-user cluster-reader -z <account-name> -n ${NAMESPACE}`
