### ISSUE TITLE
Uncler which service expose the GUI

### ISSUE THREAD

**Issue by dicolasi** [infinispan/infinispan-operator#1041]
I have deployed inifinispan using the Kubernetes operator. 
I do not want to expose an ingress for data-grid, but I have not been able to find the right service/port combination that gives me access to the GUI.

<img width="1321" alt="Screenshot 2021-05-12 at 14 40 49" src="https://user-images.githubusercontent.com/54740533/117985082-4f968a00-b330-11eb-9be9-41d51fb320e6.png">

Which one do I need to use?

**Comment by dmvolod** [comment]
@dicolasi please open a topic in the community ZulipChat https://infinispan.zulipchat.com
It will be much faster with the wide of the community

**Comment by dicolasi** [comment]
@dmvolod done!
