### ISSUE TITLE
Move ConfigMap and Secret hashes values from environment variables to annotations

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#1077]
It would be nice to move ConfigMap and Secrets hash values from the environment variables:
- CONFIG_HASH
- IDENTITIES_HASH
- ADMIN_IDENTITIES_HASH

to the following annotations
- checksum/config
- checksum/identities
- checksum/adminIdentities

#1076 would be nice to be implemented before

**Comment by rigazilla** [comment]
@dmvolod I'm inclined to add the annotations to the StatefulSet object, seems the easiest change to me.
Alternative is to add them to the Infinispan CR, but I can see any clear advantage on this. wdyt?

**Comment by rigazilla** [comment]
> > Alternative is to add them to the Infinispan CR, but I can see any clear advantage on this. wdyt?
> 
> @rigazilla why we need to store them in the Infinispan CR? I don't see any reason for that.

oh I mean't `I can't see any clear ... ` :D

**Comment by ryanemerson** [comment]
@dmvolod I still think this is a valid issue that should be addressed. Any reason you think it should be closed?

**Comment by dmvolod** [comment]
@ryanemerson it seems that since I left the Red Hat, I cannot make decisions on this project and my issues will be questioned any time and will not be in line with the development strategy
That's the reason, I closed all issues opened by myself. You feel free to control this project with other developers

**Comment by tristantarrant** [comment]
@dmvolod the input you have provided, and still want to provide, compatibly with your time, is still very valid and valuable. 
I understand you cannot/may not be able to contribute any further, but please do not close issues.

**Comment by dmvolod** [comment]
> @dmvolod the input you have provided, and still want to provide, compatibly with your time, is still very valid and valuable.
> I understand you cannot/may not be able to contribute any further, but please do not close issues.

@tristantarrant I'm sorry, I don't know why, but my suggestions have always been raised and questioned. I know that I am not part of your team and therefore this may be the case. This is difficult enough to accept, but perhaps I will be more careful about it so as not to destroy the team approach of the Red Hat. It looks very good and looks noticeable from the outside.
