### ISSUE TITLE
Split main E2E testsuite

### ISSUE THREAD

**Issue by Crumby** [infinispan/infinispan-operator#1117]
**Issue:** There is currently more then 20 tests running different deployments in main e2e test suite. When executing all the tests outside of CI (eg. OpenShift certification) any test failure will immediately halt rest of the test execution. With that many tests in single test file it's hard to tell which were executed and re-execute only those that were not.

**Proposal:** Split the main e2e test suite in several, logically grouped tests.

It'd be ideal if golang wouldn't halt test execution on failure but I haven't find a way to achieve this behavior yet.

**Comment by ryanemerson** [comment]
> When executing all the tests outside of CI (eg. OpenShift certification) any test failure will immediately halt rest of the test execution.

I have created https://github.com/infinispan/infinispan-operator/issues/1217 to address this issue.

**Comment by Crumby** [comment]
@ryanemerson #1217 aside, wouldn't it still make sense to reasonably split the main test file into several grouped by a topic to simplify navigation between the tests? Currently the `main_test.go` file is on almost 1500 lines of code and it's going to go larger

**Comment by ryanemerson** [comment]
:+1: I totally agree that some kind of grouping/splitting would be better. Even within these groups it would be better if a single failure did not result in test execution being abandoned, which is why I created #1217 as a separate issue.
