### ISSUE TITLE
Unable to configure persistent instance

### ISSUE THREAD

**Issue by ctron** [infinispan/infinispan-operator#113]
To me it looks like it is not possible to configure a persistent storage backend for Infinispan when deploying with the Infinispan operator and OLM.

**Comment by galderz** [comment]
@ctron There are two main layers where we use persistent storage for Infinispan. One is the internal storage for things like permanent cache configurations created on the fly and in-memory data when doing a graceful shutdown. The other is when you plug a cache with a persistent backend, e.g. Cassandra or similar.

For the internal storage, we'll add support for that in the next major version of the operator. For cache data persistence, you might be able to do that if using a cache store implementation that is shipped with the server and you configure it with the right settings.

What is your use case?

**Comment by ctron** [comment]
Sorry for the late response:

Actually both :grin: … So we have the Infispan server, with a persistent backend. We also use the index, with protobuf. We would expect that everything we store, is persistent. Right now I think the operator does not create PVs for the statefulset.

**Comment by galderz** [comment]
@ctron PVs are available starting with 1.0.1 (see #126).

**Comment by ctron** [comment]
> @ctron PVs are available starting with 1.0.1 (see #126).

Cool, I will check it out!

**Comment by rigazilla** [comment]
solved by #126
