### ISSUE TITLE
ConfigMap changes on update cause startup failures

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1150]
Currently the `config_controller#Process` function always reconciles the ConfigMap state regardless of whether an upgrade will be scheduled. If a future operator version introduces a Infinispan config change that is not compatible with the old image version, then this will cause the Infinispan pods to fail when they restart during the gracefulshutdown process, which ultimately causes the cluster upgrade to fail.

**Comment by dmvolod** [comment]
> If a future operator version introduces a Infinispan config change that is not compatible with the old image version, then this will cause the Infinispan pods to fail when they restart during the gracefulshutdown process, which ultimately causes the cluster upgrade to fail.

This means that Pods could be restarting during upgrade before new image is placed inside StatefulSet. Mostly it's not a problem with the configuration controller but a bit lack of logic in the upgrade procedure.

**Comment by ryanemerson** [comment]
> This means that Pods could be restarting during upgrade before new image is placed inside StatefulSet. Mostly it's not a problem with the configuration controller but a bit lack of logic in the upgrade procedure.

Exactly. This is a problem with the current GracefulShutdown approach and was the primary motivation for creating #1154. If this behaviour didn't exist, then #1126 would have been sufficient on it's own to fix the upgrade failures.
