### ISSUE TITLE
Backport support for static XSite configuration to 2.0.x

### ISSUE THREAD

**Issue by ericot** [infinispan/infinispan-operator#1156]
I'm currently running Keycloak 14.0.0 in cross-datacenter replication mode with Infinispan 11.0.9, which is the latest [recommended](https://www.keycloak.org/docs/latest/server_installation/#setting-up-cross-dc-with-infinispan-11-0-9) version, configured as a remote cache with cross-site replication enabled. For this I'm using Infinispan Operator 2.0.x, which is the latest version that supports Infinispan 11 according to the [documentation](https://infinispan.org/docs/infinispan-operator/2.0.x/operator.html).

Instead of using Kubernetes/OpenShift tokens I want to use static URIs, which is not supported until later releases of the operator. The reason for this is that static URIs are easier to configure (may be subjective) and that it will allow me to use a separate ingress controller.

**Comment by rigazilla** [comment]
@ericot, I've discussed this with @ryanemerson and it turned out that Keycloak should also work with newer version of Infinispan (i.e. 2.1.x). This allows you to have static xsite configuration out of the box with 2.1.x operator.
Can you consider this option?

**Comment by ericot** [comment]
If Infinispan 12 (operator 2.1.x) is compatible with the 11.0.9 driver used by WildFly 23 (Keycloak >= 13) I would much prefer to use the latest operator release possible.

I will update my deployment and see if I run into any problems with 2.1.x.

**Comment by ryanemerson** [comment]
> I will update my deployment and see if I run into any problems with 2.1.x.

@ericot Did you get this to work Ok? If so I will close this issue and the accompanying PR.

**Comment by ericot** [comment]
@ryanemerson I've successfully started Infinispan 12 with the operator and connected Keycloak, so initial tests seems to indicate that the versions are compatible. I will not be able to run more thorough tests until next week, but you can close this issue and the associated PR.

**Comment by ryanemerson** [comment]
Thanks for the update @ericot, I'm glad it appears to be working.
