### ISSUE TITLE
Set podManagementPolicy to Parallel for ephemeral deployment

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#1196]
If `spec.Service.Container.EphemeralStorage == true` we could utilize Parallel `podManagementPolicy` for the StatefulSet as graceful shutdown doesn't make sense in this case

**Comment by ryanemerson** [comment]
I don't think we can do this. The default StatefulSet pod management policy ensures that pods are scaled up/down one at a time. This is an important characteristic for Infinispan's data consistency as it helps prevent too many data owners leaving the cluster at once, resulting in data loss. For example, if a distributed-cache has num_owners=2 and the cluster is scaled down by two replicas with a non-parallel strategy, then it's possible for both owners to leave the cluster before data re-balancing occurs.
