### ISSUE TITLE
Testsuite: Utilise testing.Fail instead of panic

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1217]
Currently all of our tests are failed by using `panic()`. Instead, we should leverage the `.Fail()` and `.FailNow()`[0] commands. This will allow subsequent tests to continue executing after a failure.

[0] https://pkg.go.dev/testing#B.Fail
https://ieftimov.com/post/testing-in-go-failing-tests/

**Comment by Crumby** [comment]
We should go even further and leverage available packages for testing providing various assert function. Currently all the asserts in the tests are custom methods calling `panic()`. Testify assert package seems to provide great amount of various assert functions https://pkg.go.dev/github.com/stretchr/testify/assert.
