### ISSUE TITLE
Changing `spec.image` does not cause reconciling

### ISSUE THREAD

**Issue by Photonios** [infinispan/infinispan-operator#1223]
https://github.com/infinispan/infinispan-operator/blob/aec1a7e179bceed9f9df74336df4c3b856595515/pkg/controller/infinispan/infinispan_controller.go#L809

`upgradeRequired` required only looks at `DEFAULT_IMAGE` which is derived from the operator configuration. `spec.image` is completely ignored.

**Comment by dmvolod** [comment]
@Photonios yes, this is by-design as we don't provide support for custom images. They are just for testing purposes only.

**Comment by Photonios** [comment]
This would be good to add to the documentation here: https://infinispan.org/docs/infinispan-operator/main/operator.html#specifying-server-image_services

Why are custom images for testing only? For the lack of a better option, we actually built a custom image with the JDBC driver baked in. It is also useful to deploy our custom image so we can apply patches before they are released if needed.

**Comment by dmvolod** [comment]
> For the lack of a better option, we actually built a custom image with the JDBC driver baked in. It is also useful to deploy our custom image so we can apply patches before they are released if needed.

There is an option for upload custom specific libraries and files into the image without custom image build. Please use this option for that
https://infinispan.org/docs/infinispan-operator/main/operator.html#deploying-code

**Comment by Crumby** [comment]
@Photonios Custom images don't work with OLM Operator upgrades. You'd end up with updated Operator but the server would remain the same which would result in unpredictable behavior.

**Comment by Photonios** [comment]
> > For the lack of a better option, we actually built a custom image with the JDBC driver baked in. It is also useful to deploy our custom image so we can apply patches before they are released if needed.
> 
> There is an option for upload custom specific libraries and files into the image without custom image build. Please use this option for that
> https://infinispan.org/docs/infinispan-operator/main/operator.html#deploying-code

This was our initial approach. There are a few downsides:

1. Copying the JDBC driver into the pod was cumbersome to automate with the tooling we are using to manage our infra (Terraform + Helm).

2. Persistent volumes are backed by EBS volumes in AWS, which cannot be mounted across different nodes. Our cluster is big enough to run across multiple nodes. Read-only volumes _can_ be mounted on multiple nodes, but that would've meant creating the volume from a snapshot that already has the JDBC driver baked in. Alternatively, we could've deployed the EFS CI in our cluster, which _does_ allow being mounted in r/w mode to multiple nodes. Both options are cumbersome.

Creating a custom image that has the driver baked in was the easiest way to get it all working without having to resort to any of the options above.

---

> @Photonios Custom images don't work with OLM Operator upgrades. You'd end up with updated Operator but the server would remain the same which would result in unpredictable behavior.

We're aware of this and consider it our own responsibility to make sure we don't run a server version that is incompatible with the operator. If we upgrade the operator, we'd also upgrade the server image.

We resorted to modifying `RELATED_IMAGE_OPENJDK` in the operator configuration to change the server image. If we perform an upgrade, we can also upgrade the image there.
