### ISSUE TITLE
Enable Authorization configuration

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#123]
Following proposals in configuration [v3](https://github.com/infinispan/infinispan-operator/pull/108).

Implement configuration, make sure the values are passed to Infinispan and test it. 

Testing requires the integration testsuite to be in place.

**Comment by rigazilla** [comment]
Related issue infinispan/infinispan-images#57

**Comment by ryanemerson** [comment]
Once https://github.com/infinispan/infinispan-images/issues/114 has been implemented, this should just be a case of adding the roles spec definined in the Infinispan CR to the yaml file which is passed to the image.

So `spec.Security.roles` is passed as is to the image. As the operator will allows require permissions "ALL", it's necessary to add a role, e.g. "OperatorRole" with these permissions and configure operator user to have this role.
