### ISSUE TITLE
Include upgrade test in CI

### ISSUE THREAD

**Issue by gustavonalle** [infinispan/infinispan-operator#1231]
Include a step in the CI to perform upgrade tests. Probably it's enough to test upgrade from the latest released version to the code in ```main```. Also consider making the test part of the single test command described in https://github.com/infinispan/infinispan-operator/issues/1230

**Comment by ryanemerson** [comment]
OLM upgrade tests added in https://github.com/infinispan/infinispan-operator/pull/1248
