### ISSUE TITLE
Replace Rice box with golang embed

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1242]
https://pkg.go.dev/embed

Requires upgrading to go `1.16.x`.

**Comment by rigazilla** [comment]
should be good for runtime, but maybe we could have problem building downstream?

**Comment by ryanemerson** [comment]
> If we are going to change this back to use Fedora, I need clearance from EXD and product.

IMO the benefits of migrating to 1.16 aren't worth this hassle.

My vote is to wait for [1.16 to be available in RHEL 8](https://access.redhat.com/solutions/6160942).

**Comment by ryanemerson** [comment]
UBI 8.5 now includes go 1.16, so we should be able to upgrade without issue.

**Comment by ryanemerson** [comment]
https://github.com/infinispan/infinispan-operator/pull/1925
