### ISSUE TITLE
Allow to edit rollover policies for logging to the end user via infinispan CR

### ISSUE THREAD

**Issue by durgeshanaokar** [infinispan/infinispan-operator#1275]
Infinispan CR doesn't  provide flexibility to update the rollover policies in the log4j2.xml, which controls the logging for Infinispan cluster.
As of now we can only update the logging categories and logging level. However, with default logging policies, if a pod is generating more than 100MB or say 300MB of logs daily. It is possible to face issues with ephemeral storage and may lead to shortage of space for pod.

Can we provide a functionality or any changes in specs, which could allow user to add either new policies or update the default log4j2.xml and add DefaultRolloverStrategy so at the log files will be under controls during long run of the pods.

**Comment by ryanemerson** [comment]
Will be resolved by https://github.com/infinispan/infinispan-operator/issues/1364

**Comment by ryanemerson** [comment]
It's now possible to define custom logging policies by providing a custom log4j.xml file  https://github.com/infinispan/infinispan-operator/pull/1417
