### ISSUE TITLE
Create Infinispan client library that can support multiple Infinispan versions

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1313]
# Problem
The operator currently relies on the `ClusterInterface` for all interactions with the Infinispan server. As the needs of the operator has increased, this has become a collection of disparate methods for interacting with various aspects of the Infinispan lifecycle. Furthermore, the current implementation of this interface is is tightly coupled to a specific version of the Infinispan server, which will be too inflexible when support for multiple server versions is required.

# Proposal

## Interface
Replace the `ClusterInterface` with a new `Infinispan` interface that has various sub-interfaces that group Infinispan functionality. For simplicity and symmetry, the grouping can be based upon the URL scheme of the Infinispan REST API.

`pkg/infinispan/client/api/infinispan.go`:
```golang
type Infinispan interface {
	Container() Container
	Cluster() Cluster
	Logging() Logging
	Server() Server
}

type Container interface {
	Cache(name string) Cache
	Members() ([]string, error)
	Backups() Backups
	Restores() Restores
	Xsite() Xsite
}

type Backups interface {
	Backup(name string, config *BackupConfig) error
	BackupStatus(name string) (Status, error)
}

type Restores interface {
	Restore(name string, config *RestoreConfig) error
	RestoreStatus(name string) (Status, error)
}

type Cache interface {
	Create(config string, contentType mime.MimeType) error
	CreateWithTemplate(templateName string) error
	ConvertConfiguration(config string, contentType, reqType mime.MimeType) (string, error)
	Delete() error
	Exists() (bool, error)
	UpdateConfig(config string, contentType mime.MimeType) error
}

type Cluster interface {
	GracefulShutdown() error
	GracefulShutdownTask() error
}

type Logging interface {
	GetLoggers() (map[string]string, error)
	SetLogger(loggerLevel string) error
}

type Server interface {
	Stop() error
}

type Xsite interface {
	PushAllState() error
}

type Status string

const (
	// StatusSucceeded means that the operation has completed.
	StatusSucceeded Status = "Succeeded"
	// StatusRunning means that the operation is in progress.
	StatusRunning Status = "Running"
	// StatusFailed means that the operation failed.
	StatusFailed Status = "Failed"
	// StatusUnknown means that the state of the operation could not be obtained, typically due to an error in communicating with the infinispan server.
	StatusUnknown Status = "Unknown"
)

type BackupConfig struct {
	Directory string `json:"directory" validate:"required"`
	// +optional
	Resources BackupRestoreResources `json:"resources,omitempty"`
}

type RestoreConfig struct {
	Location string `json:"location" validate:"required"`
	// +optional
	Resources BackupRestoreResources `json:"resources,omitempty"`
}

type BackupRestoreResources struct {
	// +optional
	Caches []string `json:"caches,omitempty"`
	// +optional
	Templates []string `json:"templates,omitempty"`
	// +optional
	Counters []string `json:"counters,omitempty"`
	// +optional
	ProtoSchemas []string `json:"proto-schemas,omitempty"`
	// +optional
	Tasks []string `json:"tasks,omitempty"`
}
```

## Code structure
```bash
pkg
├── curl
│   └── curl.go
├── infinispan
│   ├── client
│   │   ├── api
│   │   │   └── infinispan.go
│   │   ├── factory.go
│   │   └── v13
│   │       ├── backups.go
│   │       ├── caches.go
│   │       ├── container.go
│   │       ├── infinispan.go
│   │       ├── logging.go
│   │       ├── restores.go
│   │       └── server.go
```

## Implementation
The `pkg/infinispan/client/factory.go` contains a factory method that takes the following as parameters and returns a `api.Infinispan` implementation:
- Curl client to allow HTTP requests
- Infinispan Version
  - Until multi-version support is required, we can omit this.

The factory method can then provide different version implementations of the sub-interfaces as required depending on the Infinispan version the operator is interacting with.

```go
type infinispan struct {
	cluster api.Cluster
	container api.Container
	logging   api.Logging
	server    api.Server
}

func (i Infinispan) Cluster() api.Cluster {
	return i.cluster
}

func (i infinispan) Container() api.Container {
	return i.container
}

func (i infinispan) Logging() api.Logging {
	return i.logging
}

func (i infinispan) Server() api.Server {
	return i.server
}

// New Factory to obtain Infinispan implementation. In the future this can be updated to allow a version parameter to be
// specified, with version specific implementations of sub-interfaces returned if REST API changes are required.
func New(curl curl.CurlClient) api.Infinispan {
	return infinispan{
		cluster: v13.Cluster(curl),
		container: v13.Container(curl),
		logging:   v13.Logger(curl),
		server:    v13.Server(curl),
	}
}
```

In the future, if Infinispan `14.x` updates the Logger REST API, then we can introduce `pkg/client/v14/logging.go` to handle this and the factory method can use the `v14.Logger(..)` implementation if a `14.x` server is detected.

Furthermore, if only a single Logging endpoint has been updated, it's not necessary for all of the `Logger` interface methods to be duplicated for `v14`, instead we can delegate to the `v13` implementation where required.

## API Evolution
The `pkg/infinispan/client/api` must be updated if any new methods are required. Consequently, it's also necessary to add methods to the older interface implementations that may not support this feature (it may not have existed on the old server). To facilitate this, we can introduce a `error` that is thrown if the method is called on a unsupported server version. Calls to unsupported methods should not occur, as the Operator will have to have version specific logic where there is a difference in capabilities, however returning an `error` will make such bugs more explicit and aid debugging.

**Comment by rigazilla** [comment]
I like the proposal, +1 by me

Just thinking aloud: could this design also help with the development of unit tests? I mean facilitate mocks/stubs/fakes creation?


Great description @ryanemerson !

**Comment by ryanemerson** [comment]
> Just thinking aloud: could this design also help with the development of unit tests? I mean facilitate mocks/stubs/fakes creation?

Potentially yes. My intention is to also update our `HttpClient` interface so that it does not have `podName` as a parameter, then we can use that same interface for our test rest client, which will allow us to use the `Infinispan` interface in our tests and remove all of the custom REST calls we currently have.
