### ISSUE TITLE
Ensure compatibility with Istio and other side-car architectures

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1384]
The operator currently assumes that only a single container exists in the Infinispan pods, which is not the case when deployed to a Istio enabled cluster as the istio sidecar is injected. We need to update the following:

- All PodSpec container logic should retrieve existing containers by name, not an assumed index
- `pkg/http/curl/curl.go` should be updated so that requests are sent to a specific container

**Comment by travisghansen** [comment]
https://github.com/infinispan/infinispan-operator/issues/2175
