### ISSUE TITLE
E2E tests redundancy

### ISSUE THREAD

**Issue by Crumby** [infinispan/infinispan-operator#1404]
`main` e2e tests currently contains tests that can be considered redundant and add up to the total execution time while providing minimal to zero added value.

**TLS:**
* `TestTLSWithExistingKeystore`
* `TestClusterFormationWithTLS`
Difference between the two above is one running 1 replica while the other runs 2 replicas. The latter is a stronger case of the first one. If the first one fails then the second one fails too. Thus having `TestClusterFormationWithTLS` should enough.

**Graceful Shutdown**
* `TestPermanentCache`
* `TestCheckDataSurviveToShutdown`
The two tests are testing basically the same thing. One is verifying the cache exists and is usable after graceful shutdown when created with `PERNAMENT` (which is default for some time now). The other checks that the cache exists and data were not lost with persistence configured. In this case the later is again stronger case and there is no added value by first one.

**Basic**
* `TestNodeStartup`
* `TestClusterFormation`
While there is a subtle difference where the first one tests also label propagation it's not clearly communicated out in the test name and if the node startup fails then all the tests fails. This two could be merged in a single 'SmokeTest' with a single deployment that would execute subtests on that deployment (verify clustering, label and other possible defaults).

**External service**
* `TestExternalService`
* `TestExternalServiceWithAuth`
All the tests are exposing external service and thus test it. Added value in those tests may be explicit configuration of user secrets by the later one but the test should be renamed. Default user verification could be included in the `SmokeTest` deployment above.

**Comment by ryanemerson** [comment]
@Crumby Thanks for taking the time to evaluate the current state of the tests. I agree with all of the proposed test removal/updates.
