### ISSUE TITLE
Use CodeReady Containers within CI pipeline

### ISSUE THREAD

**Issue by Crumby** [infinispan/infinispan-operator#157]
Actual CI pipeline uses custom build OpenShift4 images for spinning up OpenShift 4.0 beta version. Better option would be to use [CodeReady Containers](https://github.com/code-ready/crc) that are getting regular updates to latest OpenShift and we don't have to maintain them.

**Comment by ryanemerson** [comment]
Closing as outdated. The CI now uses `kind` clusters as they are lightweight and quick to provision.
