### ISSUE TITLE
Update example on adding custom roles and permissions

### ISSUE THREAD

**Issue by dvagnero** [infinispan/infinispan-operator#1573]
https://gist.github.com/tristantarrant/4187bf9d06e97d7913e3da20cba9c276#file-infinispan-yaml-L136

**Comment by ryanemerson** [comment]
@dvagnero Closing as the docs are correct for the Infinispan CR. The underlying problem experienced by the user was https://github.com/infinispan/infinispan-operator/issues/1578.

**Comment by dvagnero** [comment]
Thanks for the info Ryan
