### ISSUE TITLE
Docs: Add operand version attribute

### ISSUE THREAD

**Issue by dvagnero** [infinispan/infinispan-operator#1715]
We need to introduce a new attribute. The `spec.version` field in product requires server version and the tag.

**Comment by ryanemerson** [comment]
@dvagnero @dfitzmau In the future don't create an issue if there's no description, this doesn't add any value to the community and is a waste of your time. 

Of course, if you can provide a meaningful description for your work beyond the commit message please create an issue as it's useful to have a history of what motivated the changes.

**Comment by dvagnero** [comment]
Solved
