### ISSUE TITLE
Add Infinispan version to the cluster custom resource definition

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#18]
Currently the infinispan version is hardcoded, we want it to be configured by the user in the CR deployment yaml file

**Comment by galderz** [comment]
Rather than infinispan version, image URL is more useful here. Image includes not only the version, but can also be used to test snapshot/custom images.

**Comment by rigazilla** [comment]
closed by https://github.com/infinispan/infinispan-operator/pull/25
