### ISSUE TITLE
Add replication factor to cache service

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#180]
This allows users to configure the default replication factor for the default cache created for the cache service (#134). By default this is set to `1`.

**Comment by galderz** [comment]
See #179 for an idea on how to implement this.

**Comment by rigazilla** [comment]
I'm implementing this in #378. 
The default value will be 2 to allow autoscale to scale down without loosing data.

**Comment by oraNod** [comment]
@rigazilla should we close this issue as it is implemented with #378?
