### ISSUE TITLE
Enable connector encryption by default

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#190]
In some Kubernetes environments, such as OpenShift, it's possible to enable connector encryption by default since a CA can be accessed.

The operator should check if running on OpenShift, and if running with the default profile (or any other profile that requires it), enable connector encryption by default.

In vanilla Kubernetes environments, such as Minikube, connector encryption could be disabled by default, or let's encrypt could be used in those situations.

**Comment by rigazilla** [comment]
We could check if `/apis/operator.openshift.io/v1/servicecas` has entries, in that case a serving certificates service should be available and we can use that service by default.
In the other cases the user must provide the secret with certificates to enable TLS.

@galderz , @Crumby wdyt?

**Comment by galderz** [comment]
@rigazilla Sounds good
