### ISSUE TITLE
Change the default timestamp format in the operator logging

### ISSUE THREAD

**Issue by pruivo** [infinispan/infinispan-operator#1962]
The following options are available:

https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.12.3/pkg/log/zap#Options

It looks like we need to configure the `TimeEncoder` in https://github.com/infinispan/infinispan-operator/blob/main/main.go#L20
```
// TimeEncoder specifies the encoder for the timestamps in log messages.
// Defaults to EpochTimeEncoder as this is the default in Zap currently.
```

**Comment by ryanemerson** [comment]
Resolved by  #2024
