### ISSUE TITLE
Issue while performing hotrod rolling upgrade from 14.0.19 to 14.0.20 version

### ISSUE THREAD

**Issue by lakshmi-hv** [infinispan/infinispan-operator#1980]
I am trying to upgrade the infinispan from version 14.0.19 to 14.0.20 but getting below error and says it is in staging process.

1.7066110859800143e+09 ERROR controllers.Infinispan HotRodRollingStageSync failed, retrying {"infinispan": "distributed-cache-tenant/accelerex-testapp-testing-cdt-cluster", "error": "failed to sync data for cache'___protobuf_metadata': unexpected HTTP status code (500): unexpected error syncing data, response: ISPN000287: Unauthorized access: subject 'null' lacks 'ADMIN' permission"}

**Comment by lakshmi-hv** [comment]
here is another usecase where I am trying to upgrade cluster from 14.0.19 to 14.0.20 with hotrodrolling upgrade type and upgrade is not completed, below is the error message

ISPN028014: The '___protobuf_metadata' cache does not support commands of type org.infinispan.commands.write.ComputeCommand
at org.infinispan.marshall.exts.ThrowableExternalizer.readMessageAndCause(ThrowableExternalizer.java:258)
at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:182)
at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:44)
at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

**Comment by ryanemerson** [comment]
[ISPN-15651](https://issues.redhat.com/browse/ISPN-15651) should resolve the issue and has been fixed in Infinispan `14.0.25.Final`
