### ISSUE TITLE
'displayName' is mandatory field in crd specDesriptors 

### ISSUE THREAD

**Issue by Crumby** [infinispan/infinispan-operator#208]
Every description in [specDescriptor](https://github.com/infinispan/infinispan-operator/blob/master/deploy/olm-catalog/infinispan-operator.clusterserviceversion.yaml#L191) has to have `displayName` filed otherwise operator's installation fails with:
`spec.customresourcedefinitions.owned.specDescriptors.displayName in body is required`

Affects 1.0.1 release

**Comment by rigazilla** [comment]
Thank you @Crumby!

https://github.com/operator-framework/community-operators/pull/865
https://github.com/operator-framework/community-operators/pull/824
