### ISSUE TITLE
make the operator available as S2I application

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#21]

**Comment by galderz** [comment]
Why?

**Comment by rigazilla** [comment]
Seems to me it could provide an easy way for people to try the operator from source code

**Comment by galderz** [comment]
What problem are you trying to solve? I've seen Kube/OpenShift APIs for interacting with a cluster. They have their use but they're just plain maven dependencies.

**Comment by rigazilla** [comment]
not a problem, I just want to verify if that can be useful for what I said above

**Comment by rigazilla** [comment]
obsolete
