### ISSUE TITLE
Support development & testing on ARM64

### ISSUE THREAD

**Issue by andrey-dubnik** [infinispan/infinispan-operator#2106]
Hi,

I've been going through the setup on Mac ARM64 and have hit few issues around container images used in the env bootstrap and Tests not built for ARM/multi-arch. 

In order to get x86 working on Mac ARM CPU I needed to use Rosetta which needs VZ in oppose to QUEMU. Unfortunately when it comes to using VZ I have hit a likely bug with lima (I'm using Rancher Desktop) matching the description of [colima issue](https://github.com/abiosoft/colima/issues/973) which prevented `kind` from communicating with a Host DNS service. So I have reverted back to QUEMU and partial testing so I could install all the required components.

Following services were not available for ARM (can be more):

- `infinispan-test/registry:2`
- `infinispan-test/kindest-node`
- `openshift-scale/nginx`

Another issue was with k8s version being `v1.24.15`, it failed to boot for x86 and ARM for me also it didn't seem to differentiate between the arch so I have switched to `v1.28.9` version which did the job.

Can you please consider adding following?

1. building the multi-arch or ARM specific test images
2. bump up the k8s version if possible to at least `1.28`

**Comment by ryanemerson** [comment]
> building the multi-arch or ARM specific test images

We don't want the additional maintenance overhead of supporting multi-arch images, as we only host our own images under `infinispan-test` to avoid issues with the docker rate limiter.

As a workaround, I have created a PR which allows all of the images to be specified via Env variables so you can use those provided by docker hub.

> bump up the k8s version if possible to at least `1.28`

Unfortunately we can't do this as we need to test against older K8s versions that we still support. I can make this configurable via an Env variable.

Please see https://github.com/infinispan/infinispan-operator/pull/2109 and let me know if that's sufficient for your needs.

**Comment by andrey-dubnik** [comment]
Thanks! That will suffice.
