### ISSUE TITLE
Move build from the 'dep' to 'mod' golang dependencies manager 

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#234]
It would be nice to move build from 'dep' to 'mod' golang dependencies manager.
@rigazilla what do you think about it. I can take care on migration, if community decide to do this.
Thanks in advance.

**Comment by rigazilla** [comment]
Hey @dmvolod, the migration to go modules is on the path.
We already have a commit for that in #232, as you can see from the discussion the idea is to create a separate pr.
It would be great if you'd like to help us with that: cherry-picking the commit in a new PR and add anything needed. wdyt?

**Comment by dmvolod** [comment]
Thanks, @rigazilla  for pointing.
Yes, I can see right now that another guy already started to work on similar issue in PR. 
But it's not so easy as @slaskawi implemented right now as will broken code generation and Docker images with moving form dep to mod. May be he can concentrate on CRD, and me on migration from dep to mod as I already did some migration peaces.

**Comment by rigazilla** [comment]
@dmvolod, it's ok by me if you create your go modules PR. I would say please design it so it will be easy to rebase @slaskawi CRD's work on top.
Please also comment the @slaskawi PR with your concerns about the go modules. Sebastian is off this week, but I'm sure he is interested in your opinion.
Thanks!
