### ISSUE TITLE
Custom auth should not require operator user to be provided

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#240]
The user should only have to worry about user credentials. If the user provides a custom secret with no `operator` credentials, operator fails to get the correct status:

```
Errors: example-infinispan-0: no operator credentials found Views:
```

You can temporarily workaround by adding `operator` to the credentials but should not be necessary. That's an internal user. 

We should also be careful with our own internal username. We should maybe use something that is not likely to clash with something the user provides. I think we should rename it to `org.infinispan.operator` so that it's clearly namespaced.

**Comment by rigazilla** [comment]
I see your point, on the other hand is it ok to create additional credentials on the user system behind the scenes?
Not a problem now but other issues could arise if authentication will be delegated to an external system i.e. keycloak.

**Comment by galderz** [comment]
> I see your point, on the other hand is it ok to create additional credentials on the user system behind the scenes?

What other choice do we currently have if we want to have an operator user? @ryanemerson? As it stands, if we want to have an operator user, we need to pass that, along with any other users, in the same identities yaml file to the image.

Ideally we wouldn't need this operator user at all... but I think we do.

> Not a problem now but other issues could arise if authentication will be delegated to an external system i.e. keycloak.

Good remark. At first glance, the external system should be indepedent of the operator user. That is, the operator user would always be provided via user/pass independent of how the end-user identities are handled. Is that doable? @ryanemerson?

**Comment by ryanemerson** [comment]
> Ideally we wouldn't need this operator user at all... but I think we do.

I'm not sure we can avoid it tbh.



> Good remark. At first glance, the external system should be indepedent of the operator user. That is, the operator user would always be provided via user/pass independent of how the end-user identities are handled. Is that doable?

I'm not sure it's possible to have two types of authentication when delegating to keycloak, as everything has to be defined with keycloak. @tristantarrant any thoughts?

**Comment by rigazilla** [comment]
see also #303 for this

**Comment by ryanemerson** [comment]
Closing as the operator credentials no longer have to be provided as part of the user secret.
