### ISSUE TITLE
Improve x-site implementation

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#260]
The current x-site operator design, where a LoadBalancer can talk to any node, could potentially cause issues (aside from WARN messages from the load balancer heartbeats to the pods).

Instead, an alternative design based on gossip routers has been proposed (details can be found in [this JGroups blog post](http://belaban.blogspot.com/2019/12/spanning-jgroups-kubernetes-based.html)).

**Comment by rigazilla** [comment]
x-site improved by #424 and related
