### ISSUE TITLE
Datagrid Operator in OperatorHub on OpenShift does not install

### ISSUE THREAD

**Issue by madorn** [infinispan/infinispan-operator#277]
Not sure this is the right place to report but Data Grid Operator on embedded OperatorHub within OpenShift is broken when installing on a OpenShift 4.4 cluster (currently dev, GA for 4.4 will be March 2020). OpenShift 4.4 is based on Kubernetes 1.17 which has deprecated the apps/v1beta1 api endpoint for StatefulSets.

When operator spins up you see the following which causes the Operator pod to crash:

`{"level":"error","ts":1580188689.0489707,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":{"Group":"apps","Kind":"StatefulSet"},"error":"no matches for kind \"StatefulSet\" in version \"apps/v1beta1\""`

The Datagrid Operator image should be updated to use `apiVersion: apps/v1`, `kind:StatefulSet`

**Comment by rigazilla** [comment]
Thanks  @madorn 
the place is fine since the bug affects the community version also :)
