### ISSUE TITLE
Operator Details missing cluster

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-operator#283]
![pasted_image](https://user-images.githubusercontent.com/32749632/74039401-a25cf580-49b9-11ea-82e2-1fce7a86240b.png)

as in the attached screengrab:
 
"Infinispans" > "InfinispanClusters"
"Create Infinispan" > "Create Infinispan Cluster"

**Comment by galderz** [comment]
This is coming from the CRD name, which is Infinispan rather than InfinispanCluster. We could add InfinispanCluster and deprecate Infinispan, but it'd need to be managed since it'd affect user CR definitions.

**Comment by rigazilla** [comment]
There also a displayName field in the CSV file, maybe we can play with that

**Comment by dmvolod** [comment]
Look like displayName only affects on the CRD's title, not create button. I will try to open an issue with OCP console to check it.

![image](https://user-images.githubusercontent.com/24249373/75753346-9e638f80-5d3b-11ea-8752-f48815c12916.png)

**Comment by galderz** [comment]
Maybe comes from `singular` in https://github.com/infinispan/infinispan-operator/blob/master/deploy/olm-catalog/infinispans.infinispan.org.crd.yaml?

**Comment by dmvolod** [comment]
@rigazilla is this issue fixed already?

**Comment by dmvolod** [comment]
Closing, as looks like this is already resolved
