### ISSUE TITLE
Add label to service

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#285]
Service hasn't any label.
It would be good to have at least:
- a label to select all services related to all the infinispan CRs
- a label to select the service related to a specific infinispan CR

**Comment by dmvolod** [comment]
@rigazilla do we need to label another auto generated items, like configmap and secret?

**Comment by rigazilla** [comment]
> @rigazilla do we need to label another auto generated items, like configmap and secret?

Yeah right, we should have labels to select every object related to an Infinispan cluster.

**Comment by dmvolod** [comment]
Do we need to update this issue or create a new one?

**Comment by rigazilla** [comment]
I think this one is ok
