### ISSUE TITLE
Move entities model outside the infinispan_controller code

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#290]
@rigazilla , @galderz what do you think about some refactor to move entities model (create and delete services, configmaps and statefulset ) outside the infinispan_controller.go to the separate model package?

The stages are:

- [x] Stage I - move only  some simple methods and introduce constants
- [x] Stage II - move common functions from infinispan_controller to the separate packages. Arrange Status structs for Cluster and Cache (change from string to metav1.ConditionStatus in Cluster)
- [ ] Stage III - implement model (secrets, services, configmap) outside infinispan_controller. Use common list function kubernetes.GetK8sResources (possible give a new name), use common functions as much as possible (change IsConditionTrue in autoscale.go to IsWellFormed), move all entities (Service, ConfigMaps, etc.) name templates to the constants and templating instead of the values concatenation
- [ ] Stage IV - try to split kubernetes and cluster entities
- [ ] Stage V - simplify using kubernetes client and possible to use https://github.com/redhat-cop/operator-utils

**Comment by rigazilla** [comment]
@dmvolod look great to me! infinispan_controller.go really need a downsizing
