### ISSUE TITLE
Increase RequeueAfter interval as constant or multiplicator each reconcile 

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#305]
On the huge cluster the startup time of the one Infinispan node with default CPU limits still about
**Infinispan Server 10.1.2.Final started in 15916ms**
We should increase RequeueAfter interval as constant or multiply it by 2 every reconcile state as we can see a large number of iterations on bootstrap in the operator log

{"level":"info","ts":1583304923.3194888,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: 8.0.0.ER4-6-g3b15baf","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304923.319542,"logger":"controller_infinispan","msg":"Configuring the StatefulSet","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304923.4219995,"logger":"controller_infinispan","msg":"Creating identity secret","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304923.4220781,"logger":"controller_infinispan","msg":"Creating a new Secret","Request.Namespace":"my-project","Request.Name":"example-infinispan","Secret.Name":"example-infinispan-generated-secret"}
{"level":"info","ts":1583304923.5307214,"logger":"controller_infinispan","msg":"Security set","Request.Namespace":"my-project","Request.Name":"example-infinispan","Spec.EndpointSecretName":"example-infinispan-generated-secret","Status.EndpointSecretName":"example-infinispan-generated-secret"}
{"level":"info","ts":1583304923.5307539,"logger":"controller_infinispan","msg":"Creating a new ConfigMap","Request.Namespace":"my-project","Request.Name":"example-infinispan","ConfigMap.Name":"example-infinispan-configuration"}
{"level":"info","ts":1583304923.536818,"logger":"controller_infinispan","msg":"Creating a new StatefulSet","Request.Namespace":"my-project","Request.Name":"example-infinispan","StatefulSet.Name":"example-infinispan"}
{"level":"info","ts":1583304923.5770628,"logger":"controller_infinispan","msg":"Created Service","Request.Namespace":"my-project","Request.Name":"example-infinispan","Service":{"namespace":"my-project","name":"example-infinispan-ping"}}
{"level":"info","ts":1583304923.5771012,"logger":"controller_infinispan","msg":"End of the StetefulSet creation","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304923.5771525,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: 8.0.0.ER4-6-g3b15baf","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304923.577204,"logger":"controller_infinispan","msg":"Reconciling Infinispan: update case","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304923.6775675,"logger":"controller_infinispan","msg":"Pods IPs are not ready yet","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304923.6776214,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: 8.0.0.ER4-6-g3b15baf","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
.
.
.
about 30 records with "Pods IPs are not ready yet"
.
.
.
{"level":"info","ts":1583304958.6930635,"logger":"controller_infinispan","msg":"Reconciling Infinispan: update case","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304958.693129,"logger":"controller_infinispan","msg":"Pods IPs are not ready yet","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304959.6933746,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: 8.0.0.ER4-6-g3b15baf","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304959.693496,"logger":"controller_infinispan","msg":"Reconciling Infinispan: update case","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304959.7001848,"logger":"controller_infinispan","msg":"notClusterFormed","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304959.7002792,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: 8.0.0.ER4-6-g3b15baf","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
.
.
.
about 25 records with "notClusterFormed"
.
.
.
{"level":"info","ts":1583304984.7119243,"logger":"controller_infinispan","msg":"Reconciling Infinispan: update case","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304984.7120125,"logger":"controller_infinispan","msg":"notClusterFormed","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304985.1970778,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: 8.0.0.ER4-6-g3b15baf","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304985.1971421,"logger":"controller_infinispan","msg":"Reconciling Infinispan: update case","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304985.1972907,"logger":"cluster_util","msg":"get cluster members","Request.Namespace":"my-project","Secret.Name":"example-infinispan-generated-secret","Pod.Name":"example-infinispan-0","url":"http://10.128.2.26:11222/rest/v2/cache-managers/default/health"}
{"level":"info","ts":1583304985.875255,"logger":"controller_infinispan","msg":"createDefaultCache","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304986.064249,"logger":"controller_infinispan","msg":"calculated maximum off-heap size","Request.Namespace":"my-project","Request.Name":"example-infinispan","size":96468992,"container max memory":536870912,"memory limit (bytes)":536870912,"max memory bound":67525906432}
{"level":"info","ts":1583304986.67987,"logger":"cluster_util","msg":"create cache completed successfully","Request.Namespace":"my-project","Secret.Name":"example-infinispan-generated-secret","Pod.Name":"example-infinispan-0","http code":200}
{"level":"info","ts":1583304986.6799383,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: 8.0.0.ER4-6-g3b15baf","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304986.6799972,"logger":"controller_infinispan","msg":"Reconciling Infinispan: update case","Request.Namespace":"my-project","Request.Name":"example-infinispan"}
{"level":"info","ts":1583304986.6801684,"logger":"cluster_util","msg":"get cluster members","Request.Namespace":"my-project","Secret.Name":"example-infinispan-generated-secret","Pod.Name":"example-infinispan-0","url":"http://10.128.2.26:11222/rest/v2/cache-managers/default/health"}

![image](https://user-images.githubusercontent.com/24249373/75854181-a33e4700-5e00-11ea-90e3-d8fde3c1ea8f.png)

**Comment by dmvolod** [comment]
Of cause, the start time depends on CPU powerful and limits. I gave 2000m to node and get following startup time
[0m07:14:45,418 INFO  (main) [org.infinispan.SERVER] ISPN080001: Infinispan Server 10.1.2.Final started in 8016ms

**Comment by galderz** [comment]
Yeah, more CPU can help, but I'm hoping number of threads use by Infinispan goes down over time cos in a non-container env it starts way quicker than that. Also, it'd be interesting what the startup time would be if it were a Deployment instead of Stateful Set. However, if we were Deployment we'd not (out of the box) be able to store cache definitions in persistence and have them again on restart, we'd not be able to do upgrades in the current form, taking advantage graceful shutdown. It'd also have potentially issues with multiple pods being brought down at the same time...etc.

**Comment by dmvolod** [comment]
Thanks for response, @galderz 
Yes, Deployment maybe help us with speedup, but right now we have update problem with Stateful Set also #313

**Comment by dmvolod** [comment]
In https://github.com/redhat-cop/quay-operator i saw, that users error messages (secret not found, or anything else) are sent to the Events log (Home -> Events in the console).
@rigazilla , @Crumby what do you think about it for logs like https://github.com/infinispan/infinispan-operator/blob/18a3f6f7ce01bde95970b26934bb5f7e84970929/pkg/controller/infinispan/infinispan_controller.go#L1350 ?

**Comment by Crumby** [comment]
@dmvolod That be actually very helpful. It'd make issues easier to spot.

**Comment by rigazilla** [comment]
> In https://github.com/redhat-cop/quay-operator i saw, that users error messages (secret not found, or anything else) are sent to the Events log (Home -> Events in the console).
> @rigazilla , @Crumby what do you think about it for logs like
> 
> https://github.com/infinispan/infinispan-operator/blob/18a3f6f7ce01bde95970b26934bb5f7e84970929/pkg/controller/infinispan/infinispan_controller.go#L1350
> ?

Good idea @dmvolod. I think we can start publish this specific event. Should we track this in a proper issue?

**Comment by rigazilla** [comment]
@dmvolod sorry, I've just seen you already opened an issue :)

**Comment by rigazilla** [comment]
I'm working on this: extending the delay is actually trivial.
but I'm wondering why, after the statefulset has been created, we have two reconcile requests around in the same millisecond:
```
{"level":"info","ts":1585245120.3893054,"logger":"controller_infinispan","msg":"End of the StetefulSet creation","Request.Namespace":"pv-deletion","Request.Name":"example-infinispan"}

{"level":"info","ts":1585245120.389367,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: undefined","Request.Namespace":"pv-deletion","Request.Name":"example-infinispan"}
{"level":"info","ts":1585245120.3894713,"logger":"controller_infinispan","msg":"Reconciling Infinispan: update case","Request.Namespace":"pv-deletion","Request.Name":"example-infinispan"}
{"level":"info","ts":1585245120.3895955,"logger":"controller_infinispan","msg":"Pods IPs are not ready yet","Request.Namespace":"pv-deletion","Request.Name":"example-infinispan"}

{"level":"info","ts":1585245120.399571,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: undefined","Request.Namespace":"pv-deletion","Request.Name":"example-infinispan"}
{"level":"info","ts":1585245120.3996997,"logger":"controller_infinispan","msg":"Reconciling Infinispan: update case","Request.Namespace":"pv-deletion","Request.Name":"example-infinispan"}
{"level":"info","ts":1585245120.3998199,"logger":"controller_infinispan","msg":"Pods IPs are not ready yet","Request.Namespace":"pv-deletion","Request.Name":"example-infinispan"}
```

**Comment by dmvolod** [comment]
@rigazilla I'm not sure, maybe it's triggered by this watch
https://github.com/infinispan/infinispan-operator/blob/3a81d0d33f6c479d11a4b772f30e0a141deb348f/pkg/controller/infinispan/infinispan_controller.go#L97

**Comment by rigazilla** [comment]
> @rigazilla I'm not sure, maybe it's triggered by this watch
> 
> https://github.com/infinispan/infinispan-operator/blob/3a81d0d33f6c479d11a4b772f30e0a141deb348f/pkg/controller/infinispan/infinispan_controller.go#L97

seems really plausible @dmvolod, great! I'll have a better look tomorrow, thanks!
