### ISSUE TITLE
Unable to run some of the e2e tests against OpenShift

### ISSUE THREAD

**Issue by Crumby** [infinispan/infinispan-operator#312]
Some of the e2e tests do no work with OpenShift (tested with 4.2 and 4.3). The issue started appearing after migration to Operator SDK 0.15.2 PR was merged (#293).

So far this applies for all the `*Update` tests. Request to change the parameter won't hit the OpenShift.

This issue is probably caused by Kubernetes client update.

**Comment by dmvolod** [comment]
@Crumby could you please provide full error stack from the test env.

**Comment by dmvolod** [comment]
I'm not sure that all tests could be running on any openshift remotely as for some envs is not clear and possible to expose service port. It's necessary to create a routes for this.
@rigazilla , @galderz what do you think about this?

**Comment by Crumby** [comment]
@dmvolod Tests were running fine before #293 for OpenShift on AWS you just need to set `EXPOSE_SERVICE_TYPE=LoadBalancer` to be able access the ispn cluster in there.

Here is the stacktrace of failing CPUUpdate test but it's just plain timeout:
```
$ go test -v -run CPUUpdate ./test/e2e/ -timeout 30m
=== RUN   TestContainerCPUUpdate
--- FAIL: TestContainerCPUUpdate (357.71s)
panic: timed out waiting for the condition [recovered]
	panic: timed out waiting for the condition

goroutine 216 [running]:
testing.tRunner.func1(0xc0001ce300)
	/usr/lib/golang/src/testing/testing.go:874 +0x3a3
panic(0x14238e0, 0xc0001d4830)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
github.com/infinispan/infinispan-operator/test/e2e.genericTestForContainerUpdated(0x16e9898, 0x16e98a0)
	/home/pdrobek/work/GIT/DG_QE/infinispan-operator/test/e2e/main_test.go:213 +0x4bc
github.com/infinispan/infinispan-operator/test/e2e.TestContainerCPUUpdate(0xc0001ce300)
	/home/pdrobek/work/GIT/DG_QE/infinispan-operator/test/e2e/main_test.go:144 +0x39
testing.tRunner(0xc0001ce300, 0x16e98a8)
	/usr/lib/golang/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:960 +0x350
FAIL	github.com/infinispan/infinispan-operator/test/e2e	358.053s
FAIL
```

**Comment by dmvolod** [comment]
Thanks, @Crumby 
Please try to run tests from pr #318 
Looks like there are some issues in k8s client

**Comment by rigazilla** [comment]
@Crumby can you check things against 1.1.x branch? It runs with the old sdk

**Comment by Crumby** [comment]
@dmvolod #318 seems to fix the issue. Nice job! So the issue is that infinispan resource retrieved by k8s client is missing infinispan type metadata?

@rigazilla It runs fine against 1.1.x branch kubernetes client was updated altogether with the sdk.

**Comment by dmvolod** [comment]
Yes, @Crumby it looks like very closely to the https://github.com/kubernetes/kubernetes/issues/80609

**Comment by dmvolod** [comment]
@Crumby looks like TestExternalServiceWithAuth should also fails. Please verify.

**Comment by Crumby** [comment]
@dmvolod yes, you are right. Anywhere where we call `Update` on Infinispan CR we need to set it's `kind` (`(spec|infinispan).TypeMeta=InfinispanTypeMeta`). That applies for `TestExternalServiceWithAuth` and `GracefulShutdownInfinispan` and `GracefulRestartInfinispan` methods in `test_kuberentes`

**Comment by dmvolod** [comment]
Thanks, @Crumby I'm fixed all possible issues
