### ISSUE TITLE
Cluster with two or more replicas never starts after Spec.Container properties changes 

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#313]
Steps for reproduce:
- create Infinispan CRD with replicas:2
- update any Spec.Container properties
Just one pod tries to recreate and it always in ContainersNotReady readiness state 
pr #311 creates for reproducing e2e test

**Comment by dmvolod** [comment]
Doesn't reproduce with latest operator image tag.

**Comment by rigazilla** [comment]
fixed in #348

**Comment by dmvolod** [comment]
@rigazilla do you fix this in master?
What do you think about to add rolling update test into the test suite?

**Comment by dmvolod** [comment]
Sorry, can see PR on top of master

**Comment by rigazilla** [comment]
> @rigazilla do you fix this in master?
yeah thanks! created PR #350 
> What do you think about to add rolling update test into the test suite?
Don't know, we already have tests that trigger rolling upgrade like: `TestContainerCPUUpdate`. 
We could add a test that does a sequence of rolling (how many?) upgrades, but is it something that we want to run in CI?

**Comment by dmvolod** [comment]
@rigazilla we can add test from PR #311 to the test and remove all *Update tests when we will use part of the migrated e2e to unit-tests

**Comment by rigazilla** [comment]
@dmvolod actually *Update run with a 1 node cluster, so I think it's ok to add the test. Can you adapt the PR?

**Comment by dmvolod** [comment]
Yes, @rigazilla . Push updated PR with actual test.
