### ISSUE TITLE
NodePort is hardcoded and exposed also when not needed

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#325]
Operator must set explicitly a node port only if needed and use port number from `spec.Expose` if available or default to 30222

**Comment by Crumby** [comment]
@rigazilla Can't we let OpenShift to pick up the port by default? Defaulting to 30222 will force users to set the number if they are about to deploy second cluster or the port is already taken by different app running in that environment.

**Comment by rigazilla** [comment]
@Crumby that is because of or kind setup for testing (not sure but I guess it from a comment). But you're right, let's openshift choose the port and hardcode 30222 in our tests

**Comment by galderz** [comment]
@Crumby I fixed NodePort for easier debugging.

**Comment by dmvolod** [comment]
Yes, @galderz sure, but for tests against OCP on AWS we need a flexible set of NodePort, as look like AWS LoadBalancer release port not immediately with the service remove.
@rigazilla do you have a plans to fix this for tests?

**Comment by Crumby** [comment]
@dmvolod Tests won't be an issue won't be causing an issue with #326 on AWS and using LoadBalancer. As with LoadBalancer Operator will not set node port at all.

**Comment by dmvolod** [comment]
Yes, sure @Crumby , thank you.
