### ISSUE TITLE
Test suite should use https when TLS is autoenable (ie openshift with CA service)

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#329]

**Comment by dmvolod** [comment]
@rigazilla I've already done isOpenShift for some tests in keberetes package and can cherry-pick this commit to a new branch, so we can start to work on it not from the scratch.
What do you think about it. Or we need just env variable for this option?

**Comment by rigazilla** [comment]
@dmvolod the idea is to check if infinispan.Spec.Security.EndpointEncryption.Type is not nil,
the operator should set it to "service" if a CA service is available.
I think it's the most safe way to check if TLS is enabled also can survive if we add support for CA service on other platform.

**Comment by dmvolod** [comment]
Oh, @rigazilla . It's much easiest that I thought

**Comment by rigazilla** [comment]
@dmvolod yeah all the discovery work is already done by the operator
