### ISSUE TITLE
If some of services (encryption, dns or external) can't to create a first time the cluster will never have them

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#337]
Looks like we need to rewrite some code to try create them on the next reconcile state.
We could have this issues in the tests like busy NodePort or anything else.
@rigazilla , @Crumby what do you think about it?

**Comment by Crumby** [comment]
@dmvolod I like this idea, it's very well aligned with OpenShift concept. Generally controllers should drive the resource management towards user desired state. If reconciler can't create an external service for example he should log an error in the log and attempt doing it in reasonable interval again.

When I think about it i'd consider this as a bug.

**Comment by rigazilla** [comment]
@dmvolod  +1
We designed the first version following a `create/update` policy but we really need a `reconcile` policy.
Thus:
- read spec
- match with actual status
- reconcile
- if reconcile is incomplete or has errors requeue

so I agree with you, we need this for the next major

**Comment by dmvolod** [comment]
Thanks, @rigazilla , I will update with milestone 2.0.0.
As you have implemented #325 the chance of get this issue becomes lower

**Comment by rigazilla** [comment]
I think that this can be considered solved by #495

**Comment by dmvolod** [comment]
Yes, @rigazilla , sure .
We also need to create a new issue with performing `Service.type` update, for example from `NodePort` to `Route` or anything else
