### ISSUE TITLE
Cache CR should report cluster status

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#367]
>     * not sure, but caches k8s entities could be orphans when infinispan will be deleted
Yeah, this need a better thought, but we probably need to setup a policy to report cluster status into the cache CR

I'm creating separated issues

_Originally posted by @rigazilla in https://github.com/infinispan/infinispan-operator/pull/360#issuecomment-610994677_

**Comment by dmvolod** [comment]
Closing. Cache CR plan to be deprecated
