### ISSUE TITLE
Specify PVC StorageClassName

### ISSUE THREAD

**Issue by mathianasj** [infinispan/infinispan-operator#388]
The cluster I am deploying to does not define a default storage class.  I would like to be able to specify which storage class to use as part of the CRD.

**Comment by rigazilla** [comment]
solution should be something like:
- add a storageClass field to the `infinispan.spec.service.container`
- propagate it to the persistentvolumeclaim instance.

**Comment by dmvolod** [comment]
Note: it would be nice to start this after PR #401 merging, as both require to change type struct and openAPIV3Schema
