### ISSUE TITLE
Do not set memory/CPU limits by default

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#400]
By default the operator is now setting limits for memory and CPU.
It would be better to not set limits by default and provide doc guidelines for user that cares about resources.

**Comment by dmvolod** [comment]
@rigazilla we are also calculating PV size based on memory size. What customer will do if default value size is not provided?

**Comment by ctrought** [comment]
The resources (both requests & limits) should be able to be set in the CR spec to allow owners full control over how the resources are assigned and what the upper bounds (limits) are. Yes if they are not specified, it will fall back to limit range but it would be best not to rely on this as it is a generic config that cannot be tuned per pod.

**Comment by Crumby** [comment]
@rigazilla @ryanemerson I wonder whether this one can be closed as done
