### ISSUE TITLE
Operator should install a grafana dashboard using the prometheus CRD

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-operator#407]
https://github.com/infinispan-demos/infinispan-prometheus/blob/master/infinispan-grafana-dashboard.json might provide a starting point for this but the Operator should be able to load different dashboards for various Infinispan metrics

**Comment by rigazilla** [comment]
see also https://github.com/infinispan/infinispan-operator/issues/494#issue-667623852

**Comment by dmvolod** [comment]
@rigazilla do we need to close this issue also?
