### ISSUE TITLE
Discussion: Use lightweight sidecar container for collecting data from REST/HotRod Infinispan service

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#430]
In some cases, we need to collect data from Infinispan cluster pods asynchronously and if this data has changed, notify operator performs some changes and actions. The situations are:

- Metrics change required for auto-scaling
- Cluster topology change in case of rescheduling pods on different node as original (for memory allocation rearrange). It can be done with Pods and StatefullSet events trigger but many other cases could occur
- Create and remove caches and cache templates via REST or Hot Rod interface (we need to manipulate Cache CR in this case)

We can use lightweight sidecar container for this job or as alternative create a separate thread pool puller for each cluster for all cases, but lightweight sidecar is much prefer as sidecars shares network and storage with main container and much performs polling much faster than remote calls from operator side.

Also, as sidecar we can also implements REST proxy for some methods which can manipulate entities both in the Infinispan cache and Kubernetes CR's.

@rigazilla what do you think about it?

**Comment by dmvolod** [comment]
@ryanemerson could you please to look at this discussion, may be you have another ideas or some opportunities to extend core Infinispan functions. In ideal way it would be nice to have events in Infinispan core for all actions and capture them from the operator side. Polling is an option, but for me this is not good idea. wdyth?

**Comment by ryanemerson** [comment]
I don't think this approach will work in a Multi-namespace environment where a single operator instance exists. If the namespace where a CR is created does not have access to the operator namespace, then it will not be possible for the sidecar to notify the operator.

> * Cluster topology change in case of rescheduling pods on different node as original (for memory allocation rearrange). It can be done with Pods and StatefullSet events trigger but many other cases could occur

Event triggers seems like the correct way of achieving this to me.

> * Create and remove caches and cache templates via REST or Hot Rod interface (we need to manipulate Cache CR in this case)

The two way mapping of caches and a CR instance does not really scale. It also makes it difficult to configure caches as currently it requires the mixing of yaml and xml. We're discussing replacing the Cache CR with a Batch CR that either succeeds or fails; with resources (caches, counters) created via a Batch Cli script.

**Comment by dmvolod** [comment]
> The two way mapping of caches and a CR instance does not really scale. It also makes it difficult to configure caches as currently it requires the mixing of yaml and xml. We're discussing replacing the Cache CR with a Batch CR that either succeeds or fails; with resources (caches, counters) created via a Batch Cli script.

Oh, sure,thanks for sharing info @ryanemerson 
I will close this discussion as new CR plant to be implemented and it doesn't make sense
