### ISSUE TITLE
Add disable flag to the 'autoscale' section

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-operator#435]
@rigazilla as idea, maybe we can also add enable flag to the  _autoscale_ section as it contains several options. When user will try to playground with this options, it would be nice to easy enable/disable without add/remove spec section.

_Originally posted by @dmvolod in https://github.com/infinispan/infinispan-operator/pull/429_

**Comment by rigazilla** [comment]
Discussed in #429 
Sounds a good improvement, maybe we can add a disable flag so it's not showed by default
