### ISSUE TITLE
Operator needs rights to create Route/Ingress

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#437]

**Comment by dmvolod** [comment]
@rigazilla looks like we can close this issue as you are fixed it in #438
P.S. You can easy add keywords to commit/PR for automatically issue closing if one PR equals one issue
https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#:~:text=Closing%20an%20issue%20in%20the%20same%20repository,merged%20into%20the%20default%20branch.

**Comment by dmvolod** [comment]
I'm closing this issue, as rights have be fixed
