### ISSUE TITLE
The operator should configure CORS properties at ISPN server startup

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#446]
Infinispan console does cross origin calls when accesses the server REST API.
To make everything work the final console URL (the one used in the browser to access the console) must be passed to the ISPN server at startup.
Operator should be able to guess the console url in advance

**Comment by gustavonalle** [comment]
I don't think there is need to do anything in the operator. The console always calls the the REST API from the same URL as it is loaded from, so there is no CORS involved. 
There is a fix that needs to be done in netty though: https://github.com/netty/netty/pull/10382

**Comment by rigazilla** [comment]
Great news @gustavonalle , thank you!
Closing for now
