### ISSUE TITLE
Add Cache to OperatorHub.io CRDs

### ISSUE THREAD

**Issue by gordillo-ramon** [infinispan/infinispan-operator#458]
in 2.0.0, there is only infinispans listed in the main page. Attached screenshot:

![CRDs](https://user-images.githubusercontent.com/8056605/86273618-d9ce7780-bbd0-11ea-8ed6-b79f654ff572.png)

**Comment by dmvolod** [comment]
@gordillo-ramon now the issue has been fixed in 2.0.1 and I'm closing it
![image](https://user-images.githubusercontent.com/24249373/86960329-04d44080-c168-11ea-8a8c-c5855ee0162d.png)
