### ISSUE TITLE
Operator version is not consistent in log

### ISSUE THREAD

**Issue by gordillo-ramon** [infinispan/infinispan-operator#460]
Hi.

When deploying latest operator (`image: quay.io/infinispan/operator:2.0.0.Final-1`), I can see in the logs:

```
{"level":"info","ts":1593624891.4167356,"logger":"controller_infinispan","msg":"Reconciling Infinispan. Operator Version: 2.0.0.Alpha1-24-gfbe2688-dirty","Request.Namespace":"infinispan","Request.Name":"infinispan-minimal"}
```

So the version (Alpha1) is not consistent with the image (Final-1)

**Comment by dmvolod** [comment]
Yes, @gordillo-ramon , you are right
@rigazilla looks like image was building from the not clean master branch

**Comment by rigazilla** [comment]
yeah, CI was down today. I've build it locally from master but I didn't checkout the tag.
I'll rebuild tomorrow from CI
