### ISSUE TITLE
Move from 'latest' to the specific Infinispan server image tag name

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#469]
As the operator starts to depend on specific Infinispan server features (logs changing via REST, host bindings, etc.) we should bind  an image name to the specific release, not infinispan/server:latest
Also, on dev stage, we should use latest dev Infinispan server rather than stable previous build

**Comment by rigazilla** [comment]
> As the operator starts to depend on specific Infinispan server features (logs changing via REST, host bindings, etc.) we should bind an image name to the specific release, not infinispan/server:latest

I think we can revert [this commit](https://github.com/infinispan/infinispan-operator/commit/5e61b9e160e2f7bc74cf7953e7c45e0fe60d20c0#diff-5e5f804a8ee2fb8c81711b728eb5a21d) to bind release operator to a fixed operand release.

> Also, on dev stage, we should use latest dev Infinispan server rather than stable previous build
I can't find where are we referring the stable previous release
