### ISSUE TITLE
CacheService: default cache eviction size has wrong set with low memory

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#471]
Eviction size computation gives unpredictable result (unsigned subtraction overflow) if pod has low memory limit.

I this case the operator should either returns an error from the reconcile loop or starts infinispan without eviction size limit.

**Comment by dmvolod** [comment]
@rigazilla it also get unpredictable results, as all calculations are performing against node, where podList.Items[0] is scheduling. This means in case of pod re-scheduling or any others moving or decreasing number of nodes. We should define an algorithm which is not related on whole node start options. For example, user defined values or calculated with formulas, and if we can fit  with these values, go next, if not, try to reduce amount of requested memory and try to fit again.

**Comment by rigazilla** [comment]
@dmvolod if it's ok to you, let's discuss new ideas for cache sizing in #470.

In this PR I would like to just fix current behaviour: I would go for the option to return an error if memory is not enough.

**Comment by dmvolod** [comment]
Oh, yes, @rigazilla moving to the discussion issue

**Comment by dmvolod** [comment]
@rigazilla should we close this issue?

**Comment by rigazilla** [comment]
Now the operator blocks the cluster startup if pods are configured with insufficient memory
