### ISSUE TITLE
Able to use server-native image

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#473]
Operator is not able to run native image due following JDK options are not supported on it
- MaxRAM
- UseSerialGC
- MinHeapFreeRatio
- MaxHeapFreeRatio

Image: quay.io/infinispan/server-native:11.0.1.Final

We should detect/define that operator is running native image and don't set these options by default
@rigazilla wdyt?

Thanks the colleague of mine, @dsevost which is finding this during Quarkus demo preparation
https://github.com/e2e-openshift-demos/quarkus-demo/blob/b-step-03_4/jdg/datagrid-operator-setup.sh#L58

**Comment by dmvolod** [comment]
@rigazilla I'm awaiting feedback from you which option is better for us: define or detect native image running.

**Comment by rigazilla** [comment]
@dmvolod I would go with user explicit define, we can add detection later.

**Comment by dmvolod** [comment]
Planning about to play with utils like `pidof` to detect runtime automatically rather than create a separate option
Maybe we will need a status filed only for this option.

**Comment by dmvolod** [comment]
Native image 11.0.3.Final seems to start 127.0.0.1 by default. Need to be validated and open issue in infinispan-images

**Comment by dmvolod** [comment]
@ryanemerson what do you think about to place this logic to the image side or keep it on the operator side?

**Comment by ryanemerson** [comment]
IMO the JDK options should be set by the operator based upon the image in use. The user shouldn't have to worry about these things.

**Comment by dmvolod** [comment]
Yes, agreed, but i talked about to filter some unexpected Java options inside the image run script. Can this be an option?

**Comment by ryanemerson** [comment]
We could do that, but I don't think it's the correct approach. The operator is not the only consumer of the image, so I don't think it's correct for this filtering to occur there. It's better that the user is aware that a provided option is not valid with a graal native executable and update their args accordingly.

**Comment by dmvolod** [comment]
Yes, agree with you again. But I'm looking for method to keep operator configuration parameters simpler and done as much as possible options automatically. For example we can introduce an optionally env var on the native image side, i.e. GRAAL_VM_EXCLUDE_OPTIONS set it for all images by default in the operator. For other operator consumers this will be clear.

**Comment by ryanemerson** [comment]
I don't like the idea of adding such logic in the image, as the user of the native image should be providing correct java options in the first place, so adding support for an additional env variable in the image is a bit of hack imo.

I think this should be handled in the operator transparently. For now we can update `types_util#GetJavaOptions` to simply check if `ispn.Spec.Image` contains the string `infinispan/server-native` and set the args accordingly. AFAIK `Spec.Image` is mainly for dev purposes, so this would just be an interim solution until we properly support the operator with the native server.

**Comment by dmvolod** [comment]
> I think this should be handled in the operator transparently. For now we can update `types_util#GetJavaOptions` to simply check if `ispn.Spec.Image` contains the string `infinispan/server-native` and set the args accordingly.

Yes, agreed. Let's minimize parameters impacting with just image name validation. I think `native` word present is enough.
