### ISSUE TITLE
Branch 2.0.x and use master for 2.1.x devs

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#480]
A new branch for 2.0 is needed.

proposed steps:
- [x] Create the 2.0.x branch
- [x] In 2.0.x update URLs (in README and around) to refer to branch
- [x] Branch https://github.com/infinispan/infinispan-simple-tutorials
- [x] Add in the discussion all the feature that we want in 2.1
- [x] Add 2.1.0 milestone to the agreed features

**Comment by rigazilla** [comment]
I've added an intial version of the simple tutorial here:
https://github.com/infinispan/infinispan-simple-tutorials/tree/operator-2.0.x/operator

**Comment by dmvolod** [comment]
@rigazilla do you think that tutorials master should also point to the master 2.0.x or latest but not to the 1.0.x?

**Comment by rigazilla** [comment]
> @rigazilla do you think that tutorials master should also point to the master 2.0.x or latest but not to the 1.0.x?

yeah, it makes sense to update master, I'll arrange a pr

**Comment by rigazilla** [comment]
PR for simple tutorial created here:
https://github.com/infinispan/infinispan-simple-tutorials/pull/112

**Comment by rigazilla** [comment]
Preliminary issues list for 2.1.0:
https://github.com/infinispan/infinispan-operator/milestone/11
