### ISSUE TITLE
Refactor Reconcile loop

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#489]
Current loop has been designed with the assumption that if the StatefulSet is not found then all the resources need to be created from scratch.

Wherever is possible this must be changed in the common reconcile policy:
```
foreach resource:
if resource doesn't fit the CR
   then apply an adequate reconcile policy
```

**Comment by dmvolod** [comment]
@rigazilla we can probably to continue re-factoring core code to split entities from the business login in this issue
