### ISSUE TITLE
Catalog: update to the new bundle format

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#492]
Operator should be published with the new bundle format

**Comment by ryanemerson** [comment]
I'm first going to upgrade the operator-sdk version in order to better make use of the latest tooling. As part of this work, it's also necessary to convert the old package-manifests in the [community-operators](https://github.com/operator-framework/community-operators).

**Comment by ryanemerson** [comment]
Bundle format added as part of #1221

OperatorHub catalog: https://github.com/pulls?q=is%3Apr+author%3Aryanemerson+archived%3Afalse+is%3Aclosed
OCP catalog: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/236
