### ISSUE TITLE
Change to pointers all the optional structs in .Spec

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#498]
In the Infinispan CR optional fields represented by complex struct must be changed to pointer otherwise `optional` and `omitempty` attributes doesn't work

**Comment by dmvolod** [comment]
It seems to be related to the #448
// +optional are related to the OpenAPI 3.0 schema generation
https://github.com/kubernetes-sigs/kubebuilder/issues/479

**Comment by dmvolod** [comment]
Seems to already implemented for all structures. Closed
