### ISSUE TITLE
Failed to reload Infinispan status occurs inside TestContainer*Update

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#500]
We need try to investigate why this stack trace occurs inside tests. Tests are passes, but need to check

{"level":"error","ts":1596126050.2651718,"logger":"controller_infinispan","msg":"failed to reload Infinispan status","Request.Namespace":"infinispan-operator","Request.Name":"test-node-startup","error":"Infinispan.infinispan.org \"test-node-startup\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/dvolodin/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/infinispan/infinispan-operator/pkg/controller/infinispan.(*ReconcileInfinispan).Reconcile\n\t/u01/git/infinispan/infinispan-operator/pkg/controller/infinispan/infinispan_controller.go:715\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/dvolodin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/dvolodin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/dvolodin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/dvolodin/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/dvolodin/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/dvolodin/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}

[TestContainerCPUUpdateWithTwoReplicas.log](https://github.com/infinispan/infinispan-operator/files/5002587/TestContainerCPUUpdateWithTwoReplicas.log)

**Comment by rigazilla** [comment]
I should not be a problem, it is probably due to the fact that the test deletes the Infinispan CR while the Reconcile func is executed.

**Comment by dmvolod** [comment]
Yes, sure, this test looks like delete CR behaviour
