### ISSUE TITLE
[question] Operator not applying new version of Infinispan 

### ISSUE THREAD

**Issue by bordeuax** [infinispan/infinispan-operator#505]
I am doing Infinispan upgrade from version `11.0.0.Final-2` to `11.0.1.Final`. 
* Update Infinispan CRD with image `infinispan/server:11.0.1.Final ` 
* Operator log 
`{"level":"info","ts":1596202176.9734375,"logger":"controller_infinispan","msg":"Pod iothub-datagrid-1 runs wrong image infinispan/server:11.0.0.Final-2 != infinispan/server:11.0.1.Final","Request.Namespace":"hono","Request.Name":"iothub-datagrid"}`

* Operator version 
`jboss/infinispan-operator:2.0.0.Alpha1`

*Question*
* Why the operator not doing automatically Infinsipan pod upgrade ?

**Comment by dmvolod** [comment]
@bordeuax , yes, you are right, it's not implemented now with manual install inside single operator version.
We are planning to implement this option

**Comment by bordeuax** [comment]
@dmvolod , thanks for your feedback. So, I patched K8S statefulsets, generated by infinispan operator, with new image and as a result i had a zero-down time roiling update. My questions are; if are some best practices to handle such cases, i also observed that updating the caches  with same parameters i have quasi the same behavior.

**Comment by dmvolod** [comment]
@bordeuax right now the only one solution is updating DEFAULT_IMAGE env variable on the operator level to have a desired behavior. The patching K8S Statefulset is not a best practice, as when operator will be fully functional, it will return the original Statefulset parameters back.Please note, that the Infinispan server image will be update for the all clusters in the project/namespace.

**Comment by bordeuax** [comment]
I updated  `DEFAULT_IMAGE` env variable. But, I observed that the operator doing upgrade by gracefully shutting down the current cluster, but when we are changing statefulset we have a behavior of rolling restart/update. 

@dmvolod, 
* Having upgrade by gracefully shutting down, is a normal behavior ? 
* Cache update also need gracefully shutting down or cache update is on the fly.

**Comment by rigazilla** [comment]
@bordeuax we currently support upgrade only via graceful shutdown.
Rolling upgrade can't be done just upgrading pods in the running cluster,
Infinispan docs for a zero downtime upgrade is [here](https://infinispan.org/docs/dev/titles/upgrading/upgrading.html#rolling_server_upgrades)
I think that the main constraint here is that running different Infinispan versions in the same cluster is not supported, though it can works for some releases.

What are your use case requirements? Do you think the documented procedure can fits you needs?

**Comment by bordeuax** [comment]
My use case is related to IoT and Infinispan have a big impact on availability of the system. Zero-Down time for infinispan for any devops activity is the main requirement. Last time i had many cases when was the need to apply different cache/data-grid config due to perf/load tuning. The doc regarding zero downtime, mentioned above, yes can help but will need more effort to implement. 
@rigazilla, can you confirm me what is the exact behavior when i want to update some cache parameters: this is applied automatically by the operator or we have some exceptions.

**Comment by dmvolod** [comment]
@bordeuax could you please explain, which parameters you want to update?

**Comment by rigazilla** [comment]
> My use case is related to IoT and Infinispan have a big impact on availability of the system. Zero-Down time for infinispan for any devops activity is the main requirement.

**Comment by bordeuax** [comment]
To create caches i am using the following CRD definition: 
```
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: cache-name
spec:
  adminAuth:
    secretName: cache-secret
  clusterName: test-cluster
  name: cache-name
  template: '
  <infinispan>
     <cache-container name="clustered" default-cache="cache-name" statistics="true">
        <transport initial-cluster-size="1" lock-timeout="60000"/>
        <replicated-cache name="cache-name" statistics="true" statistics-available="true">
        </replicated-cache>
     </cache-container>
  </infinispan>
  ' 
```
And when i want to update( the cache has been created) the cache parameters according [infinispan 11.0](https://infinispan.org/schemas/infinispan-config-11.0.xsd ), I have impression that some cache parameters are not applied and no way how i can check current cache param. 
The `curl -u operator:<operator password> https://<cluster IP>:11222/rest/v2/caches/cache-name -k ` not giving all parameters that are listed in [infinispan 11.0](https://infinispan.org/schemas/infinispan-config-11.0.xsd)

**Comment by dmvolod** [comment]
Ah, yes, @bordeuax but update cache configuration is not supported in the Infinispan REST API
https://infinispan.org/docs/11.0.x/titles/rest/rest.html

@rigazilla this is the case we were talking about, the customer wants to update the fields which is read-only by design but not validated

**Comment by bordeuax** [comment]
@dmvolod, what will be the best practices approach for the use-case when i want to update my cache configuration ? 
Recreate the cache from scratch ?

**Comment by dmvolod** [comment]
@bordeuax , I can't provide the best practice for this issue, as operator doesn't support deletion a separate cache now
You can use a REST API for this or delete a whole Infinispan cluster

**Comment by bordeuax** [comment]
@rigazilla , I tested [Infinispan docs for a zero downtime upgrade](https://infinispan.org/docs/dev/titles/upgrading/upgrading.html#rolling_server_upgrades), and for my use-case is not 100% fit. I will try to come with more details. 

I have an IoT Platform based on [Eclipse Hono](https://www.eclipse.org/hono/). 
Infinispan is used in Hono to keep `last known gateway` for devices, this mean that when a device send some data, we will update in infinispan pod-id from where this device coming. 
This information is crucial because based on this infos the business application can communicate with device. 
In case when the number of devices are more than one million and the number of pods that updating data and read is more than 100, the bottle neck for ifnispan upgrade became data synchronization:
                           `POST /v2/caches/myCache?action=sync-data `

Anyway, infinispan will be up and we will have zero-down time migration but from some customers perspective the service will be down because application was not able to communicate with devices. This down time is cause because we have inconsistency between clusters that is generated by high frequency of data updates.

**Comment by rigazilla** [comment]
> @rigazilla , I tested [Infinispan docs for a zero downtime upgrade](https://infinispan.org/docs/dev/titles/upgrading/upgrading.html#rolling_server_upgrades), and for my use-case is not 100% fit. I will try to come with more details.
> 
> I have an IoT Platform based on [Eclipse Hono](https://www.eclipse.org/hono/).
> Infinispan is used in Hono to keep `last known gateway` for devices, this mean that when a device send some data, we will update in infinispan pod-id from where this device coming.
> This information is crucial because based on this infos the business application can communicate with device.
> In case when the number of devices are more than one million and the number of pods that updating data and read is more than 100, the bottle neck for ifnispan upgrade became data synchronization:
> `POST /v2/caches/myCache?action=sync-data `

@bordeuax thanks for providing more info on the use case!

> 
> Anyway, infinispan will be up and we will have zero-down time migration but from some customers perspective the service will be down because application was not able to communicate with devices. This down time is cause because we have inconsistency between clusters that is generated by high frequency of data updates.

This seems strictly related to the sync-data procedure: I would suggest to open an issue on the Infinispan project if you have a reproducer test case or logs that shows the inconsistency
