### ISSUE TITLE
Cache CR reconciles multiple times once created

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#509]
```
{"level":"info","ts":1596562591.8567762,"logger":"controller_cache","msg":"Reconciling Cache","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562591.857102,"logger":"controller_cache","msg":"Identify the target cluster","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562592.2456076,"logger":"controller_cache","msg":"Cache already exists","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562592.2457194,"logger":"controller_cache","msg":"Update CR with owner reference info","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562592.4072902,"logger":"controller_cache","msg":"Update CR status with connection info","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562592.4608173,"logger":"controller_cache","msg":"Reconciling Cache","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562592.4609013,"logger":"controller_cache","msg":"Identify the target cluster","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562592.825822,"logger":"controller_cache","msg":"Cache already exists","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562592.8262186,"logger":"controller_cache","msg":"Update CR status with connection info","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562593.8792214,"logger":"controller_cache","msg":"Reconciling Cache","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562593.8793037,"logger":"controller_cache","msg":"Identify the target cluster","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562594.261027,"logger":"controller_cache","msg":"Cache already exists","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562594.2612426,"logger":"controller_cache","msg":"Update CR status with connection info","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562594.314239,"logger":"controller_cache","msg":"Reconciling Cache","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562594.314298,"logger":"controller_cache","msg":"Identify the target cluster","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
{"level":"info","ts":1596562594.677796,"logger":"controller_cache","msg":"Cache already exists","Request.Namespace":"infinispan-operator","Request.Name":"example-cache"}
```

**Comment by dmvolod** [comment]
@rigazilla could you please a look at this issue also, it's not so huge problem at all (only validates and invokes REST API multiple time) but I don't really understand why it reconciles about 2-3-4 times. Maybe it's by design in controller-runtime

**Comment by rigazilla** [comment]
at first sight seems that the `client.Status().Update()` call triggers all the subsequent reconcile Request.

**Comment by dmvolod** [comment]
Ops, need to be tested, but looks like trigger more times that the same Infinispan reconciler

**Comment by rigazilla** [comment]
> Ops, need to be tested, but looks like trigger more times that the same Infinispan reconciler

yes, that's true. I'm looking into

**Comment by dmvolod** [comment]
Do we need to keep this "as is" or modify behavior, for example, doing some early validates on the status?

**Comment by rigazilla** [comment]
I think it would be great to avoid all the unneeded events

**Comment by dmvolod** [comment]
As idea, we could introduce `cacheName` and `clusterName` fields in the status and validates them as early as possible to prevent full reconcile loop run. @rigazilla wdyt?

**Comment by dmvolod** [comment]
I'm also a little bit confusing if this code can thrown a reconcile loop, as Pod never owned by `infinispanv2alpha1.Cache`
https://github.com/infinispan/infinispan-operator/blob/817588187a58ba58286af39aa626a5789cf6c0db/pkg/controller/cache/cache_controller.go#L67
https://github.com/infinispan/infinispan-operator/blob/817588187a58ba58286af39aa626a5789cf6c0db/pkg/controller/cache/cache_controller.go#L69

**Comment by dmvolod** [comment]
Yes, I've found that this is expected https://github.com/operator-framework/operator-sdk/issues/1292 and we need to check status ASAP

**Comment by rigazilla** [comment]
> Yes, I've found that this is expected [operator-framework/operator-sdk#1292](https://github.com/operator-framework/operator-sdk/issues/1292) and we need to check status ASAP

Yep, thanks for the docs! This behaviour on the Infinispan CR is probably hidden by all the events coming from the statefulset.

(The watcher on the Pod for the Cache has been automatically generated by the sdk, it's really not needed)

**Comment by rigazilla** [comment]
I've create a PR #515 that reduces the reconcile requests

**Comment by dmvolod** [comment]
Close as looks like the issue has been fixed
