### ISSUE TITLE
MAKE_DATADIR_WRITABLE initContainer image should be configurable

### ISSUE THREAD

**Issue by donovanmuller** [infinispan/infinispan-operator#518]
In trying to implement the workaround for #392 I noticed that the `initContainer` image is [hardcoded](https://github.com/infinispan/infinispan-operator/blob/817588187a58ba58286af39aa626a5789cf6c0db/pkg/controller/infinispan/infinispan_controller.go#L770) to `busybox`.

Unfortunately I run in an air gapped environment and need to be able to change the image to reference an internal registry. Something similar to [`DEFAULT_IMAGE`](https://github.com/infinispan/infinispan-operator/blob/51e06b80c75de84e46c4037441ebdee86bab9b68/deploy/operator.yaml#L36) would be appreciated.

**Comment by rigazilla** [comment]
Hi @donovanmuller, can you please add a description of your k8s cluster, I would like to investigate better the issue and find a proper solution... just need to find some time

**Comment by donovanmuller** [comment]
Hi @rigazilla, sure:

[RKE](https://rancher.com/docs/rke/latest/en/) Kubernetes `1.15.11` cluster:

```
$ kubectl version
...
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

with storage provided by VMware vSAN using the [vSphere Cloud Provider](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/overview.html#kubernetes-storage-support).
