### ISSUE TITLE
Operator should support multiarch images

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#531]
The right operand image should be picked up by the operator basing on the build architecture.
See: https://github.com/keycloak/keycloak-operator/blob/master/pkg/model/image_manager.go

**Comment by dmvolod** [comment]
This doesn't handle Quarkus native or standard JDK image
Need to be combined with #520

**Comment by rigazilla** [comment]
This should be backported also on 2.0.x branch

**Comment by rigazilla** [comment]
even better to start with 2.0.x impl so there will be no interaction with #520

**Comment by dmvolod** [comment]
> even better to start with 2.0.x impl so there will be no interaction with #520

Yes, agree

**Comment by dmvolod** [comment]
I will embed this into master fix as part of the #520
