### ISSUE TITLE
TestContainerCPUUpdateWithTwoReplicas and TestExternalService fails on OCP

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#535]
--- FAIL: TestContainerCPUUpdateWithTwoReplicas (0.05s)
panic: Infinispan.infinispan.org "test-node-startup" is invalid: spec.service.type: Unsupported value: "": supported values: "Cache", "DataGrid" [recovered]
	panic: Infinispan.infinispan.org "test-node-startup" is invalid: spec.service.type: Unsupported value: "": supported values: "Cache", "DataGrid"

--- FAIL: TestExternalService (0.05s)
panic: Infinispan.infinispan.org "test-external-service" is invalid: spec.service.type: Unsupported value: "": supported values: "Cache", "DataGrid" [recovered]
	panic: Infinispan.infinispan.org "test-external-service" is invalid: spec.service.type: Unsupported value: "": supported values: "Cache", "DataGrid"

**Comment by dmvolod** [comment]
Looks like was a problem with the CRD update. Not reproduced on latest master

**Comment by redmark-alt** [comment]
@dmvolod We are seeing this failure with DG 8.2 testing e2e on Power & s390x.  Test are running from the `2.0.x` branch, are there CRD(s) that need to be applied to the `2.0.x` branch?

**Comment by dmvolod** [comment]
@redmark-alt which operator version are you testing now?

**Comment by redmark-alt** [comment]
@dmvolod It the RH 8.2.0 CR2 operator.

**Comment by dmvolod** [comment]
For this version you should run tests from the `master` branch

**Comment by redmark-alt** [comment]
@dmvolod Thanks for the details we missed the updates when we started QE testing on 8.2.0.
