### ISSUE TITLE
Package Restructure

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#568]
The current codebase has evolved over time as we became more familiar with both `go` and the `operator-sdk`. Initially the code was written to service a single controller, however we will soon have multiple CRs and controllers e.g. Backup, Cache, Infinispan and Restore. In order to better facilitate code re-use and ensure loose-coupling of components, I think we need to revisit the structure of `pkg/` and come up with an agreed notion of best practices.

[This talk](https://www.youtube.com/watch?v=MzTcsI6tn-0) that @rigazilla recommended is the basis of this proposal.

As a starting point, I propose utilising the following structure:

```
pkg
├── apis
│   ├── addtoscheme_infinispan_v1.go
│   ├── addtoscheme_infinispan_v2alpha1.go
│   ├── apis.go
│   └── infinispan
│       ├── group.go
│       ├── v1
│       │   ├── doc.go
│       │   ├── infinispan_types.go
│       │   ├── register.go
│       │   ├── types_util.go
│       │   ├── zz_generated.deepcopy.go
│       │   └── zz_generated.openapi.go
│       └── v2alpha1
│           ├── cache_types.go
│           ├── doc.go
│           ├── register.go
│           ├── types_util.go
│           ├── zz_generated.deepcopy.go
│           └── zz_generated.openapi.go
├── controller [1]
│   ├── add_cache.go
│   ├── add_infinispan.go
│   ├── backup
│   ├── cache
│       ├── cache_controller.go
│       └── default.go
│   ├── controller.go
│   ├── infinispan [2]
│   │   ├── autoscale.go
│   │   ├── infinispan_controller_fake.go
│   │   ├── infinispan_controller.go
│   │   ├── infinispan_controller_test.go
│   │   └── xsite.go
│   └── restore
├── infinispan [3]
│   ├── caches.go # All logic related to manipulating caches
│   ├── cluster.go # All cluster related types, CacheManagerInfo etc
│   ├── constants.go # Resource Urls etc
│   ├── client
│   │   └── http
│   │       ├── client.go # Contains HttpClient and HttpConfig interface
│   │       └── curl
│   │           └── curl.go # implementation
│   └── configuration
│       ├── image.go # Previously controller/utils/infinispan/configuration/
│       ├── service_site.go
│       └── xsite.go
├── launcher
│   ├── launcher.go
│   └── main.go
├── kubernetes [4] 
    ├── client.go
    ├── labels.go
    └── pods.go
```

[1] Controller package - All logic related to the manipulation of kubernetes resources should reside here. CR specififc logic should be in a sub-package named after the CR, e.g [2]

[2] Controller CR sub-package for "Infinispan" CR

[3] infinispan package - Controls all logic related to interacting with Infinispan servers. Use sub-packages to further separate this. For example, the `client` package is the root for all client implementations. Currently we only have a curl based http client, but it could be hotrod etc in the future.

[4] kubernetes package - For all generic operations related to kubernetes that are common accross our controllers. This should not contain any operator logic, just common code for manipulating kube resources. For example applying labels to a pod.should

@rigazilla @dmvolod Any thoughts?

**Comment by dmvolod** [comment]
Yes, sure, @ryanemerson 
We have already issue related to code refactoring. Let's move this proposal to it and add additional or edit currentsteps for tracking

**Comment by ryanemerson** [comment]
> We have already issue related to code refactoring. Let's move this proposal to it and add additional or edit current steps for tracking

@dmvolod Which issue do you have in mind? I couldn't find one that was directly related.

**Comment by dmvolod** [comment]
> > We have already issue related to code refactoring. Let's move this proposal to it and add additional or edit current steps for tracking
> 
> @dmvolod Which issue do you have in mind? I couldn't find one that was directly related.

Oh, the name was really strange #290 maybe you can get and move some ideas from it, close, create some steps and we will track new changes here.

**Comment by dmvolod** [comment]
@ryanemerson I look at this directory structure proposal and this looks like very flat and don't utilize package model. Packages just a directory structures and combining caches.go, cluster.go and constants.go in one `infinispan` package seems to be very simple and cause misleading. It can be, for example group all k8s entities, i.e. StatfulSet, Service's, ConfigMap's inside the `model` package separating each or group by the go file.
Along with this directory structure for the HTTP/curl looks a little bin complex and we can try to level up it or make less branchy. It can be the same if we plan to implement for example another client interaction, i.e. HotRot, etc. 
wdyt?

**Comment by ryanemerson** [comment]
So I actually got carried away on Friday afternoon and made the changes to see how it would look. I have created a draft PR for feedback. Commenting on the actual changes might make things easier. https://github.com/infinispan/infinispan-operator/pull/569

> Packages just a directory structures and combining caches.go, cluster.go and constants.go in one `infinispan` package seems to be very simple and cause misleading.

`caches.go` doesn't actually exist yet, that was just an example of how we could further split things. In the PR I have broked this down further so there is actually the following structure:

```
pkg/infinispan
├── client
│   └── http
│       ├── client.go
│       └── curl
│           └── curl.go
├── cluster.go
├── configuration
│   └── configuration.go
└── security
    └── users.go
```



> It can be, for example group all k8s entities, i.e. StatfulSet, Service's, ConfigMap's inside the `model` package separating each or group by the go file.

The purpose of the `infinispan` package was to hold all logic related to interacting with infinispan resources, not kubernetes. The logic for updating Infinispan k8s entries should be in the relevant `controller` package, which consumes both the `infinispan` and `kubernetes` packages.



> Along with this directory structure for the HTTP/curl looks a little bin complex and we can try to level up it or make less branchy. It can be the same if we plan to implement for example another client interaction, i.e. HotRot, etc.

The idea here was to create a generic `http` interface in `client.go` so that if we ever find a better solution to utilising curl on a pod, we can just add a new `impl` package in `infinispan/client/http`. Having the additional implementation package follows the golang design principles discuessed in the talk I linked and imo allows greater flexibility long term at the cost of an extra package in an import statement.

```
pkg/infinispan/client
└── http
    ├── client.go
    └── curl
        └── curl.go
```

**Comment by dmvolod** [comment]
> The purpose of the `infinispan` package was to hold all logic related to interacting with infinispan resources, not kubernetes. The logic for updating Infinispan k8s entries should be in the relevant `controller` package, which consumes both the `infinispan` and `kubernetes` packages.
Yes, it's true and I agree with you, but infinispan_controller code becomes bigger and bigger and an idea to separate model (k8s entities) outside the logic for better maintaining.

**Comment by ryanemerson** [comment]
I see what you mean. So something like:

```
pkg/controller/infinispan
├── autoscale.go
├── infinispan_controller_fake.go
├── infinispan_controller.go
├── infinispan_controller_test.go
└── model
        ├── statefulset.go
        └── services.go
```

Or were you thinking a layer higher e.g.:

```
pkg/model
├── backup
        └── services.go
├── cache
        └── services.go
└── infinispan
        └── services.go
```

**Comment by rigazilla** [comment]
I would consider also to split the infinispan_controller.go file in multiple files in the same package, it should almost contains application logic and personally I would prefer to keep everything in the same place.

**Comment by rigazilla** [comment]
The new structure looks a good starting point to me.

I'm just think about some issues that the final result should simplify... I would say
- unit tests dev (we miss them a lot!)
- new features development
- integration with available general purpose libraries for operator (just a vague idea)

**Comment by dmvolod** [comment]
Also a little bit confusing with two `infinispan` packages and would be nice to place xsite logic and meta to the separate package

**Comment by ryanemerson** [comment]
> I would consider also to split the infinispan_controller.go file in multiple files in the same package, it should almost contains application logic and personally I would prefer to keep everything in the same place.

Yeah we should definitely split this into multiple files where it makes sense. `autoscale` and `xsite` are good examples of this.

I believe abstracting the k8 entity definitions to another package, e.g. `model`, would make it so the controller code is focused entirely on the reconcile logic. It would also mean that it's much simpler to update the spec of a k8 entity as all the definititions are under the `model` package. We can the do something like the following:

```go
// model is imported model package, e.g. `pkg/model/infinispan`
entity := model.InfinispanStatefulSet(...)
// `kube` is the abstraction library that we use for interacting with kube. This could be either our own abstractions in `pkg/kube` or a general purpose library
err := kube.CreateEntity(enity)
if err != nil {
    // handle err
}
```


> * unit tests dev (we miss them a lot!)

+1. If we make better use of fine-grained interfaces, e.g. cluster or `HttpClient`, then we can then easily provide mock implementations for unit tests.



> * new features development

+1000. I created this issue and PR to help facilitate the Backup/Restore work.

**Comment by ryanemerson** [comment]
> Also a little bit confusing with two `infinispan` packages and would be nice to place xsite logic and meta to the separate package

The two infinispan packages is a consequence of the CR being called `Infinispan`, imo the fqn of `controller/infinispan` vs `infinispan` is clear.

 I guess we could have `controller/infinispan` and then `/ispn` for the infinispan related interfaces/implementations, but I think that's more confusing. Any other ideas?

The `xsite.go file` is only relevant to the infinispan CR controller, so I think having it in the `controller/infinispan` package makes sense.

**Comment by dmvolod** [comment]
> The two infinispan packages is a consequence of the CR being called `Infinispan`, imo the fqn of `controller/infinispan` vs `infinispan` is clear.

Ok, let's keep as described

**Comment by dmvolod** [comment]
@ryanemerson should we close this issue?
