### ISSUE TITLE
Conditions have both upgrade and wellFormed status set to "True" simultaneously

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#576]
There is situation during upgrade when Status.Conditions have two records with `upgrade` and `wellFormed` are set to `True` simultaneously.
In this case `kubectl wait --for condition` can't be utilized for this statuses. Yes, we can wait for `stopping` but it's easy to reset `wellFormed` on upgrade. Also we would like to document Infinispan CR status flow in design doc. 
I'm not sure that is correct behavior
@rigazilla , @ryanemerson wdyt?

```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"infinispan.org/v1","kind":"Infinispan","metadata":{"annotations":{},"name":"example-infinispan","namespace":"infinispan-operator"},"spec":{"replicas":2}}
  creationTimestamp: "2020-09-17T07:55:21Z"
  generation: 3
  name: example-infinispan
  namespace: infinispan-operator
  resourceVersion: "46518"
  selfLink: /apis/infinispan.org/v1/namespaces/infinispan-operator/infinispans/example-infinispan
  uid: 83677b56-45ea-460e-9a4a-1e5fba8572cb
spec:
  container:
    cpu: 500m
    memory: 512Mi
  image: quay.io/infinispan/server:11.0
  logging: {}
  replicas: 0
  security:
    endpointEncryption:
      certSecretName: example-infinispan-cert-secret
      certServiceName: service.beta.openshift.io
      type: Service
    endpointSecretName: example-infinispan-generated-secret
  service:
    container:
      storage: ""
    replicationFactor: 2
    type: Cache
status:
  conditions:
  - message: 'View: example-infinispan-0-64678,example-infinispan-1-1362'
    status: "True"
    type: wellFormed
  - message: ""
    status: "True"
    type: upgrade
  security:
    endpointEncryption:
      certSecretName: example-infinispan-cert-secret
      certServiceName: service.beta.openshift.io
      type: Service
    endpointSecretName: example-infinispan-generated-secret
  statefulSetName: example-infinispan
```

**Comment by rigazilla** [comment]
I've created a log of all the transitions during upgrade:
https://gist.github.com/rigazilla/17437a2bc7872c946159428b369cc795
so we can discuss any improvements.

@dmvolod what's the problem of having both `wellFormed` and `upgrade` ?

**Comment by dmvolod** [comment]
@rigazilla the single reason for reset wellFormed state when upgrade is starting, that there is a limitation for using `kubectl wait --for condition=wellFormed` immediately after upgrade procedure initiated. It's necessary to wait for next condition=stopping and than for also wellFormed. This means that customers need to take care of some intermediate states that they might not think about. I think upgrade means that cluster not wellFormed already.

**Comment by dmvolod** [comment]
@rigazilla also we have a situation, when no any condition state a present until cluster are starting from scratch, but would be nice to have. No one can define is cluster or operator alive. This is also described in #542

**Comment by rigazilla** [comment]
@dmvolod yep, having `wellFormed` true while the cluster is going to shutdown, can lead to confusion if the user uses it to check if the cluster is ready.
On the other hand cluster is really `wellFormed` until first pod goes down.
I'm wondering if it is worth adding a new explicit condition about "cluster is usable".

**Comment by dmvolod** [comment]
> yep, having `wellFormed` true while the cluster is going to shutdown, can lead to confusion if the user uses it to check if the cluster is ready.

There is no other way for checking thins
> On the other hand cluster is really `wellFormed` until first pod goes down.

Yes, true
> I'm wondering if it is worth adding a new explicit condition about "cluster is usable".

Yes, it's nice to have and will be useful for both, customers and us for validating cluster before creating cache for example, as well as backup/restore procedures

**Comment by ryanemerson** [comment]
> I'm wondering if it is worth adding a new explicit condition about "cluster is usable".

This could be good from a usability p.o.v,  but might be restrictive for our internal logic. How about a hybrid approach where we provide a generic "usable" status for users that is true when all `[x,y,z]` statuses are true?

So for example, if we had a specific status field for "wellFormed" and "shutdownInitiated", we would define usable as true when `usable := wellFormed && !shutdownInitiated`. WDYT?

**Comment by dmvolod** [comment]
@ryanemerson, yes, true, for us it can be definition like `usable := wellFormed && !shutdownInitiated` and it's good point
but for customers this field must conform k8s rules with conditions structure otherwise it it will be limited with `kubectl wait --for condition` usage.

**Comment by ryanemerson** [comment]
> but for customers this field must conform k8s rules with conditions structure otherwise it it will be limited with `kubectl wait --for condition` usage.

100% agreed. To be clear, I was suggesting that we define the condition in exactly the same way as `wellFormed` and `shudownInitiated` via `InfinispanConditions`, but the set value is determined by aggregation of the other conditions.

**Comment by dmvolod** [comment]
> 100% agreed. To be clear, I was suggesting that we define the condition in exactly the same way as `wellFormed` and `shudownInitiated` via `InfinispanConditions`, but the set value is determined by aggregation of the other conditions state.

Oh, yeah. Do you means that will no explicitly set a new introduced condition but update it each dependent condition update/set?

**Comment by ryanemerson** [comment]
Yes. The state of "usable" is recalculated by the operator whenever one of the dependent condition's values change. As we already update the conditions via various set/get methods in `api/infinispan/v1/types_util.go`, it shouldn't be too dificult to centralise this logic in the controller.

**Comment by dmvolod** [comment]
I'm closing this issue, as new IsWellFormed implementation has resolved problem
But still not supported for using DynamicClient (#580) as requires just one Condition to be listenning
