### ISSUE TITLE
If Spec.Image is defined by default it will never been updated on operator Upgrade

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#581]
When Spec.Image set by default with following code
https://github.com/infinispan/infinispan-operator/blob/23bba88eb4edbe25ed6a869552183d5c2b67f866/pkg/apis/infinispan/v1/types_util.go#L81-L85
In the future the Image name will be constant and never been updated (DEFAULT_IMAGE in the Pod will be new, but in the StatefulSet will keep the old)
https://github.com/infinispan/infinispan-operator/blob/23bba88eb4edbe25ed6a869552183d5c2b67f866/pkg/controller/infinispan/infinispan_controller.go#L662
https://github.com/infinispan/infinispan-operator/blob/23bba88eb4edbe25ed6a869552183d5c2b67f866/pkg/controller/infinispan/infinispan_controller.go#L704-L705

This will occurs while upgrade from 2.0.x to the latest master branch

**Comment by ryanemerson** [comment]
@dmvolod I'm probably missing something, but as `Spec.Image` is always set on Infinispan CR creation by the operator, is it not possible for the new operator version to simply inspect existing CRs and see that the `Spec.Image` points to an older image? and if a new cluster rollout is required, the `Spec.Image` field can simply be updated by the new operator?

**Comment by dmvolod** [comment]
> @dmvolod I'm probably missing something, but as `Spec.Image` is always set on Infinispan CR creation by the operator, is it not possible for the new operator version to simply inspect existing CRs and see that the `Spec.Image` points to an older image? and if a new cluster rollout is required, the `Spec.Image` field can simply be updated by the new operator?

Yes, @ryanemerson it can possible to update `Spec.Image` on each operator Upgrade but we can't separate this value defined by operator from the user provided. If we done this update the user defined Image will be lost. Maybe @rigazilla has another idea what we need to do in this case.

**Comment by ryanemerson** [comment]
This raises a large issue for me, which is what level of support do we offer for custom images? Imo custom images should be used purely for debugging and this should be documented.

**Comment by dmvolod** [comment]
> This raises a larger issue for me, which is what level of support do we offer for custom images? Imo custom images should be used purely for debugging and this should be documented.

I'm not sure that custom image is for debug purpose only. Customer can use it for running previous Infinispan version or native image choosing.

**Comment by dmvolod** [comment]
Ok, good, agreed!
Let's remove this value on the operator upgrade and set from the `GetDefaultImage` function. We also need to remove default `Spec.Image` configuration for better upgrade option.

**Comment by rigazilla** [comment]
I also agree to provide only a very basic support to custom image.
If possible my preferred use case for this would be:
- user runs a custom image at his own risk
- if provided a custom image is never updated
