### ISSUE TITLE
wellFormed condition isn't present until cluster is formed for the first time

### ISSUE THREAD

**Issue by Crumby** [infinispan/infinispan-operator#595]
If user creates a new Infinispan CR with replicas count eg. 5 then the `wellFormed` condition isn't present in status conditions until the cluster of 5 is formed. Expected would be to have `wellFormed` set to false since the CR initialization as from the start can be said that cluster isn't well formed yet.

**Comment by dmvolod** [comment]
@Crumby this is  slightly similar to #542. Yes, customer wouldn't know about cluster state until success formed
