### ISSUE TITLE
Operator Requires Kubernetes API Access to Remote Sites

### ISSUE THREAD

**Issue by timothymathison** [infinispan/infinispan-operator#604]
The current `Infinispan` CRD configuration for x-site replication requires remote backup sites to be specified with their kubernetes API details. My understanding is that the operator uses this to actually query the remote kubernetes API and check for the respective external service, and then lookup the host and port.

Is it possible that a configuration option could be added that would support specifying the remote backup sites `host`/`port` details directly, instead of requiring access to the kubernetes API?
Not only does this access require populating credential secrets for each remote backup site in every other kubernetes cluster, but it also requires network access to the kubernetes API from the other clusters.
In the infrastructure environment I'm working in, these network connections are currently blocked.
Allowing and authorizing these connections would have significant configuration and security downsides; so I'd rather not go down that road if at all possible.

Is there anything I'm missing with respect to the requirement for cross cluster kubernetes API access?

**Comment by dmvolod** [comment]
@pruivo , @rigazilla could you please answer if you'e missing this and it's an actual question. Thanks.

**Comment by pruivo** [comment]
Yes, that is correct. The operator inspects the remote cluster to know where the JGroups is listening to the x-site connection.

About the question, I don't know. :thinking: From my experience, Kubernetes associates a random available port to the service; and the service is started by the operator. No idea how is it possible to know the host/port beforehand.

Any ideas?

**Comment by Crumby** [comment]
@pruivo Two step configuration should be possible:
* Step one: create 0 size cluster with x-site enabled (Or a cluster with a single site)
* Step two: once the Endpoints are created and URL locations are know write them to Infinispan CR and spin up/restart cluster

> Kubernetes associates a random available port to the service

Depends on the service and platform. If you use eg. LoadBalancer on AWS then your cluster will be available by default on `someRandomString:xSitePort` where `xSitePort` is the same as target port in the container. And I think for the LoadBalancer on AWS it should be possible to have location set by user (thus the location would be deterministic before creation).

Probably would be worth to check other exposure options. Is it possible for JGroups to communicate securely over tls? If yes then passthrough route on OpenShift would be an option.

**Comment by rigazilla** [comment]
Seems a reasonable use-case to me.

Atm remote API access is mandatory, but I think we could arrange a solution.

**Comment by rigazilla** [comment]
i.e. with nodeport service the port number can be configured in advance

**Comment by timothymathison** [comment]
Yeah in my use case I'm using Azure AKS `LoadBalancer` service types, so the port(s) can all be known ahead of time.
The clusters also have [external-dns](https://github.com/kubernetes-sigs/external-dns) setup, so hosts can be assigned ahead of time to each service with `annotations`. Although, I think #597 needs to be addressed to support assigning service annotations?

**Comment by timothymathison** [comment]
Is this something that could be worked on soon? Or is it preferred that I work on it myself and open a PR?

**Comment by pruivo** [comment]
from my side, feel free to contribute to the project :+1:
