### ISSUE TITLE
Publish 2.0.4 release on operator hub

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#605]
### Relesing in hub
Providing here a description of the procedure needed to publish a new version of the operator on the hub.
This procedure is for Package Manifest Format and will be soon replaced by the new procedure based on the new bundle format.

This is a manual procedure (the release script is obsolete and a new version is needed for the bundle format).
You basically need to create 2 PR: a "community" one for OCP and an "upstream-community" for k8s.

1. git clone git@github.com:operator-framework/community-operators.git
1. cd community-operators/community-operators/infinispan
1. mkdir 2.0.4
1. update csv and crd files (see below a check list)
1. copy here csv and crd files for the release
1. cd .. 
1. update info in the infinispan.package.yaml

When everything looks fine in community clone again the repo in a different location for upstream community and copy there the changes

1. git clone git@github.com:operator-framework/community-operators.git upstream-community
1. cd community-operators/upstream-community-operators/infinispan
1. copy here infinispan.package.yaml and 2.0.4 folder

now you can issue two different PR against origin/master

### Update CSV. A check list
1. search for `quay.io/infinispan` and check if tags are updated for all the images
2. check field: `metadata.name`, `metadata.version`, `spec.version`, `spec.replaces`
3. example for CR in `metadata.annotations.alm.-examples` that maybe need update
4. operator permissions in `spec.install.spec.permissions`
5. operator cluster permissions in `spec.install.spec.clusterPermissions`
6. env variables in `spec.install.spec.deployments[].spec.template.spec.containers.env`

### Pull requests for 2.0.4
Community
https://github.com/operator-framework/community-operators/pull/2446
Upstream
https://github.com/operator-framework/community-operators/pull/2447

Don't forget to signoff the PRs.

More info on how to release: https://github.com/operator-framework/community-operators

**Comment by dmvolod** [comment]
> Don't forget to signoff the PRs.

@rigazilla could you please explain what does signoff means and how we can do this
Also, can we automate all required steps for releasing operator on hub?

**Comment by rigazilla** [comment]
> > Don't forget to signoff the PRs.
> 
> @rigazilla could you please explain what does signoff means and how we can do this

you need to commit with `-s` option. 
more info https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#sign-your-work

> Also, can we automate all required steps for releasing operator on hub?

we had a script `make release`, but it was based on some assumptions that chaged over time: disconnect install, channels struct. Also the update of the csv file was only partial. So basically automated scripts needed a lot of manual work.
We probably need a better look on the new bundle for upstream before automate things again.

**Comment by dmvolod** [comment]
This should be close. 2.0.4 published successfully to the operator hub
