### ISSUE TITLE
Can not open inifinispan console when deployed in kuberentes 

### ISSUE THREAD

**Issue by Gupta-Amrit** [infinispan/infinispan-operator#627]
I followed the documentation(https://github.com/infinispan/infinispan-operator#minikube) to install infinispan operator on Azure kubernetes service and then deployed the Infinispan cluster using https://github.com/infinispan/infinispan-operator/blob/master/deploy/cr/expose/cr_route.yaml file. Everything looks good and pods/service are up and running but when I am trying to access the infinispan console, it is redirecting to the `/console/welcome` path but after then it just opens a blank page. On looking into the browser console I am getting `Uncaught SyntaxError: Invalid or unexpected token error     app.bundle.js:2`. Moreover on looking into the pods logs I am not getting any error message. Is there any argument that needs to be added in the nginx ingress or did I missed any step.

**Comment by tristantarrant** [comment]
It's probably https://issues.redhat.com/browse/ISPN-12347
It will be fixed in 11.0.5 / 12.0.0.Dev06
