### ISSUE TITLE
ServiceAccount for Infinispan pods should be configurable

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#63]
Currently Infinispan pods run with the `infinispan-operator` account.
This account can do almost everything inside the namespace: i.e. read and write all the secrets, create/delete objects.
The result is that anyone that can login to the Infinispan pod can do dangerous actions.

The user should be able to specify the service account that will be used to run the Infinispan cluster.

**Comment by galderz** [comment]
Decided not to make service account configurable, and just use default service account.
