### ISSUE TITLE
applyLabelsToCoordinatorsPod in infinispan_controller invokes early than Pods become ready

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#630]
`applyLabelsToCoordinatorsPod` try to invoke `cluster.GetCacheManagerInfo` that requires Pod to be ready, but `!kube.ArePodIPsReady(podList)` calls later after it's code 

https://github.com/infinispan/infinispan-operator/blob/712f0b8a93bfa74272c07fed4af82e46d8bb14dd/pkg/controller/infinispan/infinispan_controller.go#L400-L407

https://github.com/infinispan/infinispan-operator/blob/712f0b8a93bfa74272c07fed4af82e46d8bb14dd/pkg/controller/infinispan/infinispan_controller.go#L409-L415

**Comment by dmvolod** [comment]
@rigazilla which branch we should backport this issue? Is 2.1.0 include this change?

**Comment by rigazilla** [comment]
@dmvolod 2.1.0 has the fix. We need a back port of #647 on 2.0.x

**Comment by dmvolod** [comment]
Oh, yes, thanks, @rigazilla Will do

**Comment by dmvolod** [comment]
Close. Issue has been fixed
