### ISSUE TITLE
Custom labels on Resources created by Operator

### ISSUE THREAD

**Issue by buehlmann** [infinispan/infinispan-operator#650]
Let the user give the possibility to add his own custom labels to resources created by the Infinispan operator.

**Comment by alvarolop** [comment]
Hello,

I want to +1 this issue. I am going to explain the reason why I would really appreciate this feature. 

I am currently setting up several Infinispan clusters on Openshift and I am monitoring them using Prometheus (The one provided on the platform). Each Business Unit uses one or more Infinispan clusters and they want to monitor them all together. 

For us, the easiest way to filter pods is using the bu_code=mybu label which is present in all the pods of each BU. Unfortunately, labels of the Infinispan CR are not propagated to the Service nor Pods. The simplest way to propagate labels to the metrics ingested in Prometheus is having those labels on the pods or the services by configuring targetLabels or podTargetLabels [1]. 

[1] https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec

I think that this feature would increase the synergy between these two projects, so much.

Is this feature planned for the future?
Regards, 
Álvaro López

**Comment by rigazilla** [comment]
I would go on implementing this use case:
- user adds it's own labels to Infinispan CR
- user set two new fields (list of label names as strings) `targetLabels` and `podTargetLabels`
- operator will propagate Infinispan CR labels in the `targetLabels` to all the managed services
- operator will propagate Infinispan CR labels in the `podTargetLabels` to all the managed pods

is this ok?

**Comment by dmvolod** [comment]
@rigazilla is there any case when set of the labels are different between Infinispan CRs for Pods and services?

**Comment by alvarolop** [comment]
Hello Vittorio,

Thank you very much. Yes, these two fields in the Infinispan CRD fulfill all of our needs (And even more).

Regarding the question of @dmvolod. Right now I cannot think about a use case where we would need different labels in services and pods, but maybe there could be in the future. For my current use case, with just labels on pods or services is enough.

Thank you very much, have a nice day!
Álvaro.

**Comment by dmvolod** [comment]
Hi, @alvarolop 
Probably, I wrote not so correct sentence, my question was about to separate labels list between Infinispan CR's or setup them globally on the Operator level.

**Comment by rigazilla** [comment]
@dmvolod imo users will like the possibility to setup labels at cluster level. I would like to provide an implementation for the global/operator level on top on that.

@alvarolop I've just used the Prometheus implementation as reference, we can simplify and use only `targetLabel` both for pods and services, if it sounds goog

**Comment by rigazilla** [comment]
> 
>     * targetLabels => Provides labels to services, and routes.
> 
>     * podTargetLabels => Provides labels to StatefulSet, ReplicationControler, and pods.
> 

@alvarolop, it looks good to me. So let's follow the Prometheus design.

**Comment by rigazilla** [comment]
@alvarolop , @dmvolod I considering to move `targetLabels, podTargetLabels` to the `.annotations` field:
- they are only related to k8s and don't affect infinispan server runtime so I think it would be great to leave them out of `.spec`
- I would like to add annotations for operator generated labels that will be propagate to resources in the same way of `ŧargetLabels, podTargetLabels`

wdyt?

**Comment by alvarolop** [comment]
Hello @rigazilla, sorry, I am on PTO until next week. Regarding the location of the labels, I do not have the experience to say if it should be under `.spec` or `.annotations`. However, I have seen the PR and I think that this covers all the possible needs, so it is good as per my understanding!

**Comment by dmvolod** [comment]
@rigazilla can we close this issue as already fixed for master and 2.0.x branches?

**Comment by rigazilla** [comment]
solved with #787 and #811
