### ISSUE TITLE
Possibility to configure K8s (anti)-affinity rules

### ISSUE THREAD

**Issue by buehlmann** [infinispan/infinispan-operator#651]
We would like to define pod anti-affinity rules so that the infinispan pods are even distributed over the nodes. 

imo the Strimzi Operator solves this in a elegant and flexible way: https://strimzi.io/docs/operators/latest/using.html#assembly-node-scheduling-deployment-configuration-kafka-node-scheduling

**Comment by dmvolod** [comment]
Closing as feature has implemented
