### ISSUE TITLE
Test TestBackupRestore/DataGrid throw error

### ISSUE THREAD

**Issue by redmark-alt** [infinispan/infinispan-operator#685]
Test TestBackupRestore/DataGrid throw error and its unclear what missing.

+ go mod vendor
+ go test -v ./test/e2e -timeout 60m
=== RUN   TestBackupRestore
=== RUN   TestBackupRestore/DataGrid
panic: no matches for kind "Backup" in version "infinispan.org/v2alpha1" [recovered]
	panic: no matches for kind "Backup" in version "infinispan.org/v2alpha1"

**Comment by dmvolod** [comment]
There is special make target is present for testing, that's prepare env before run `go test`
Please try with `make test`

**Comment by redmark-alt** [comment]
I received the same error using "make test" on master but once I switch to the 2.0.x branch it worked. Thanks you.

**Comment by dmvolod** [comment]
That's very strange for `master`
Could you please provide full log from starting `make test` for `master` on your env?

**Comment by redmark-alt** [comment]
fedora 31
git version 2.25.4
go version go1.13.15 linux/amd64

 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:infinispan/infinispan-operator.git # timeout=10
Fetching upstream changes from git@github.com:infinispan/infinispan-operator.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:infinispan/infinispan-operator.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/refs/heads/master^{commit} # timeout=10
Checking out Revision d8280e92ed639e04013c5cd61b8791e2c1ef73c9 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d8280e92ed639e04013c5cd61b8791e2c1ef73c9 # timeout=10
Commit message: "ISPN-12562 directory attributes"
First time build. Skipping changelog.
[rhdg-8-ocp-operator-test-e2e-briggs-ron] $ bash -xe /tmp/jenkins10702829445067966.sh

Using project "datagrid-suite".
+ '[' false = true ']'
+ '[' true = true ']'
+ cd infinispan-operator
+ export EXPOSE_SERVICE_TYPE=LoadBalancer
+ EXPOSE_SERVICE_TYPE=LoadBalancer
+ export KUBECONFIG=/home/fedora/.kube/config
+ KUBECONFIG=/home/fedora/.kube/config
+ export RUN_LOCAL_OPERATOR=false
+ RUN_LOCAL_OPERATOR=false
+ export TESTING_NAMESPACE=datagrid-suite
+ TESTING_NAMESPACE=datagrid-suite
+ oc new-project datagrid-suite
Error from server (AlreadyExists): project.project.openshift.io "datagrid-suite" already exists
+ echo 'Project datagrid-suite already exist'
Project datagrid-suite already exist
+ make test
./build/build.sh linux
building infinispan-operator... version 2.1.0.Dev06-9-gd8280e9
build/run-tests.sh /home/fedora/.kube/config
Using KUBECONFIG '/home/fedora/.kube/config'
=== RUN   TestBackupRestore
=== RUN   TestBackupRestore/DataGrid
panic: no matches for kind "Backup" in version "infinispan.org/v2alpha1" [recovered]
	panic: no matches for kind "Backup" in version "infinispan.org/v2alpha1"

goroutine 562 [running]:
testing.tRunner.func1(0xc000819f00)
	/usr/lib/golang/src/testing/testing.go:874 +0x3a3
panic(0x1494a00, 0xc000650b00)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
github.com/infinispan/infinispan-operator/test/e2e/utils.ExpectNoError(...)
	/home/fedora/workspace/RHDG/rhdg-8-ocp-operator-test-e2e-briggs-ron/infinispan-operator/test/e2e/utils/asserts.go:10
github.com/infinispan/infinispan-operator/test/e2e/k8s.TestKubernetes.Create(0xc000435b60, 0x18c9020, 0xc000796000)
	/home/fedora/workspace/RHDG/rhdg-8-ocp-operator-test-e2e-briggs-ron/infinispan-operator/test/e2e/k8s/kubernetes.go:135 +0xc9
github.com/infinispan/infinispan-operator/test/e2e.testBackupRestore.func1(0xc000819f00)
	/home/fedora/workspace/RHDG/rhdg-8-ocp-operator-test-e2e-briggs-ron/infinispan-operator/test/e2e/backup_restore_test.go:68 +0x416
testing.tRunner(0xc000819f00, 0xc0002d96f0)
	/usr/lib/golang/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:960 +0x350
FAIL	github.com/infinispan/infinispan-operator/test/e2e	158.940s
FAIL
make: *** [Makefile:112: test] Error 1
Build step 'Execute shell' marked build as failure
Archiving artifacts
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE

**Comment by dmvolod** [comment]
Oh, yes, thanks @redmark-alt 
This is expected behavior for `master` branch and already installed operator and `RUN_LOCAL_OPERATOR=false` option

**Comment by redmark-alt** [comment]
@dmvolod Thank you sir.
