### ISSUE TITLE
Deprecate the Cache Service

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#691]
Currently the operator provides two types service types: Cache and Data Grid.

# Status Quo
The Cache Service is a volatile service that only allows caches to be created using the default cache configuration that the user has no control over. The advantages of this service is simplicity and it allows greater assumptions to be made by the operator for auto-scaling, however in it's current form there are a number of disadvantages:

- The cache service is the default mode, so unless a user explicitly sets `service.type: DataGrid` they will have a cluster that is unable to create arbritrary caches.
- The HotRod, ClI and Console are not are of the cache services limitations, so it's possible for users to attempt actions that can't be performed (e.g. creating a cache with a new configuration) resulting in exceptions being thrown.
- Yet another barrier of entry to the user: "Which service should I choose?"
- Additional code and doc maintainence

# Proposal for Infinispan 12
1. Deprecate `spec.service.type`
2. Default to the "DataGrid" service if `spec.service.type` is not set
3. Remove the cache service in Infinispan 13

**Comment by Crumby** [comment]
There are two features tight to Cache Service currently and we should probably decide if we want provide them for what is Data Grid Service right now. Mainly:
* Memory based autoscaling (Should be available ideally for all the caches in the cluster)
* Default cache with it's settings
  * Either provided by default or via CR fields
  * Could be dropped completely as user'll need to learn other ways of creating caches anyway

Other thing that I'm thinking about with deprecation of Cache Service is that current yaml design stops making a sense a bit. Eg. you'll have `spec.service.container.storage` which would make more sense in `spec.container.storage`. Basically it seems to me that whole service block will become redundant. Redesigning it will require Infinispan/V2 though and that probably won't be simple and quick to implement (Altogether with need to support both V1 and V2 for a release or two)

**Comment by rigazilla** [comment]
Until the autoscaler based on container metrics will be available I would change the default rules like this:
2. If `spec.service.type` is not set
    2a.  If autoscale is set then default to the "CacheService"
    2b. else default to the "DataGrid"
