### ISSUE TITLE
Server no more supports http BASIC auth

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#710]
sh-4.4$ curl -i --insecure --http1.1 --basic -u operator:bta7Z7S575KLkIZ9   https://test-cluster-formation-1:11222/rest/v2/cache-managers/default/health
HTTP/1.1 400 Bad Request
content-length: 73

ISPN080052: The request authentication mechanism 'BASIC' is not supported

**Comment by tristantarrant** [comment]
BASIC is enabled implicitly only when TLS is on.

**Comment by rigazilla** [comment]
In this case TLS was enabled.
I think it's an image configuration builder setup, the infinispan.xml has an explicit:
```
            <rest-connector name="rest">
                <authentication mechanisms="DIGEST"/>
            </rest-connector>
```
but I can't see any recent change to the code.
Operator can't check if a cluster is wellformed with this issue.

**Comment by tristantarrant** [comment]
Yes, it's
https://issues.redhat.com/browse/ISPN-12576

Basic was being enabled anyway.

**Comment by rigazilla** [comment]
no more able to reproduce this issue

**Comment by dmvolod** [comment]
This is reproduced on any Travis CI test with 12.0.0.CR1 image as on k8s TLS disabled by default
PR #725 propagate this error to the `WellFormed` message

**Comment by dmvolod** [comment]
https://travis-ci.org/github/infinispan/infinispan-operator/jobs/753778188

**Comment by ryanemerson** [comment]
https://github.com/infinispan/infinispan-operator/pull/727 fixes the problem by making our curl commands utilise DIGEST authentication.

**Comment by ryanemerson** [comment]
Closing as digest authentication is now used #727
