### ISSUE TITLE
Operator Console prototyping

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#718]
Would like to get feedback about Infinispan Operator Console with following functions to be implemented

- Central view of all Infinispan clusters and related CR's across namespace
- Links to the separate clusters consoles (if exposed)
- Expose cluster console if needed
- Able to link Cache/Batch/Backup/Restore CR's to the Ininispan CR and back view

![image](https://user-images.githubusercontent.com/24249373/103551495-78f36500-4ebb-11eb-8622-7a0936fb250d.png)

**Comment by rgordill** [comment]
Very interesting, indeed, having an integrated console instead of a dozen ones. Could it be possible to add a console like this not to the operator itself, but like a infinispan-k8s-manager sort of?

I would also add a prometheus query-like view, so it can be a single pane of glass for infinispan clusters deployed in k8s.

**Comment by ryanemerson** [comment]
It's an interesting idea for sure and would be nice to have, but I wonder how many orgs will deploy multiple Infinispan clusters for this to be worth the development time.

It's already possible to view all CRs via the kubectl cli e.g. `kubectl get Infinispan --all-namespaces`

**Comment by rgordill** [comment]
Not only multiples clusters but also dozens of replicas per cluster. 

If infinispan is the cache server for microservices, it is very likely that several microservices that runs in one namespace as a part of an application used a different infinispan cluster for each microservice type as a segregation of duties.

**Comment by dmvolod** [comment]
> It's an interesting idea for sure and would be nice to have, but I wonder how many orgs will deploy multiple Infinispan clusters for this to be worth the development time.

Yeah, correct, for small org this doesn't make sense and would be nice to make console optional, for example with UI_CONSOLE env variable set to false/true
> 
> It's already possible to view all CRs via the kubectl cli e.g. `kubectl get Infinispan --all-namespaces`

Yes, agreed, but all consoles (Kubernetes UI, OpenShift UI and CodeReady Workspaces, etc.) are not for power users and users want to see and observer all entries and them links in the single pane
