### ISSUE TITLE
Core Infinispan tests should run early than Backup/Restore tests in CI

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#723]
Rename tests for correct ordering or create a common function for placing test calls in correct order

**Comment by ryanemerson** [comment]
I'm curious why this is important?

**Comment by dmvolod** [comment]
@ryanemerson the problem with digest auth you've just resolved could be find more early in simple tests as they are more granular than complex Backup/Restore tests
But due to failing Backup/Restore simple tests are not runing

**Comment by ryanemerson** [comment]
:+1: makes sense. I'm not sure renaming the tests for this behaviour is the correct way to proceed as it seems very brittle and prone to failure as the number of tests increase. Is it possible to split the `test/e2e` tests into sub-packages to achieve this separation and execution order?

In Junit it's possible to assign tests to catagories, is something similar possible in go?

**Comment by dmvolod** [comment]
> Is it possible to split the `test/e2e` tests into sub-packages to achieve this separation and execution order?
> 
> In Junit it's possible to assign tests to catagories, is something similar possible in go?

As you could see with digest implementation, the standard golang modules not so very fully functional
Seems to be no much more functionality than playing with `t.Run(...)`
Probably https://github.com/stretchr/testify could help with it
