### ISSUE TITLE
Validate StatusCode for REST calls in ClusterInterface methods

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#726]
Following methods need to be validate expected `rsp.StatusCode` before decode content to avoid unexpected behavior
- CacheNames
- GetMetrics
- GetCacheManagerInfo
- GracefulShutdown

Special function need to be created to validate expected `StatusCode` values

**Comment by ryanemerson** [comment]
@dmvolod Can you add some details to the description of the issue. The title on it's own is pretty vague.

**Comment by dmvolod** [comment]
Fixed, close issue
