### ISSUE TITLE
Readiness probe failing on caching e2e tests  "connect: connection refused"

### ISSUE THREAD

**Issue by redmark-alt** [infinispan/infinispan-operator#771]
I'm running e2e testing in the 2.0.x branch on Openshift 4.5. The readiness probe fails using the "https" but will succeed using "https" insecure.  What changes are needed to get "https" working?  Or to force the readiness probe to use "http"? 

Readiness probe failed: Get https://10.128.2.189:11222/rest/v2/cache-managers/default/health/status: dial tcp 10.128.2.189:11222: connect: connection refused

sh-4.4$ curl https://10.128.2.189:11222/rest/v2/cache-managers/default/health/status
curl: (60) SSL certificate problem: self signed certificate in certificate chain

sh-4.4$ curl http://10.128.2.189:11222/rest/v2/cache-managers/default/health/status
curl: (52) Empty reply from server

sh-4.4$ curl --insecure  https://10.128.2.189:11222/rest/v2/cache-managers/default/health/status
HEALTHY

**Comment by Crumby** [comment]
You shouldn't need to touch the probes via CURL. It's for OpenShift only to decide whether the pod is ready.

> Readiness probe failed: Get https://10.128.2.189:11222/rest/v2/cache-managers/default/health/status: dial tcp 10.128.2.189:11222: connect: connection refused

This is common event firing up when initiating new container. It just means that server isn't ready to receive requests yet.

**Comment by redmark-alt** [comment]
I was just using the curl command to show that the connection was accessible from the pod using curl with insecure.  I guess I need to find another reason for the caching tests to be failing.
