### ISSUE TITLE
2.1.x channel on OperatorHub contains all possible versions

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#780]
2.1.x Infinispan Operator channel on OperatorHub contains all possible versions, but should include 2.1.x versions only

![image](https://user-images.githubusercontent.com/24249373/106254928-58a09700-622a-11eb-948f-c5fbb6c38ab4.png)

@rigazilla could you please to have a look at this issue, I don't know about it nature

**Comment by rigazilla** [comment]
@dmvolod, I suspect the cause is that we declared replacement between channels:  i.e. 1.0.0 replaces 0.3.2.
I'll look around for more info

**Comment by ryanemerson** [comment]
I think this is correct. The dropdown is showing the entire graph of dependencies. If you go to the 2.0.x channel, the 2.1.x releases are not present.
