### ISSUE TITLE
Operator doesn't reconcile StatefulSet deletion

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#783]
The operator doesn't redeploy the stateful set if deleted by the user:

`oc delete statefulset example-infinispan`

**Comment by dmvolod** [comment]
This not reproduced on current master, probably this issue could be applied to the 2.0.x version only

**Comment by rigazilla** [comment]
@dmvolod just tried on master and it seems to be affected

**Comment by dmvolod** [comment]
Probably latest fixes add some repression
@rigazilla what is the error message in the logs?

**Comment by dmvolod** [comment]
Yeah, Deletion event from StatefulSet has been disabled

**Comment by rigazilla** [comment]
yeah @dmvolod actually the reconciler doesn't get any event
