### ISSUE TITLE
CustomerResourceDefinition must be updated to version v1

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#805]
The v1beta1 version of CustomResourceDefinition, MutatingWebhookConfiguration, and ValidatingWebhookConfiguration are being removed in 1.22 after six releases of deprecation.  In 1.22, the kube-apiserver will no longer serve the v1beta1 version of these resources and the only way to access them will be through the v1 APIs, available since 1.16.

**Comment by dmvolod** [comment]
Operator SDK should be at least v0.18.2 to support this changes

**Comment by ryanemerson** [comment]
`networking.k8s.io/v1beta1` is also impacted so we will have to update the various Ingress resources we use.

**Comment by dmvolod** [comment]
This code seems to be impacted also
https://github.com/infinispan/infinispan-operator/blob/87333d1a29051e8584ffa1f170e35a572a2c07fa/pkg/kubernetes/kubernetes.go#L165

**Comment by rigazilla** [comment]
I'm doing some experiments for this issue.
Current plan is to create a PR for `main` trying minimize the impact so to ease backport on 2.1.x

**Comment by rigazilla** [comment]
Seems it's quite safe to change the `operator-sdk` for `make codegen` to `v0.18.0`:
- it has no effect on code i.e. `operator-sdk generate k8s` does nothing
- all the CRD are updated to `v1`

**Comment by rigazilla** [comment]
Tested a manual crd update with a running ispn cluster and it worked smoothly:
- OPERATOR_SDK_VERSION=v0.16.0 make codegen
- oc apply -f deploy/operator-install.yaml 
- oc apply -f deploy/cr/minimal/cr_minimal.yaml 
- OPERATOR_SDK_VERSION=v0.18.0 make codegen
- oc apply -f deploy/operator-install.yaml
- cluster runs without problems 
- oc edit infinispan example-infinispan
- change something
- CR is reconcilied

**Comment by dmvolod** [comment]
We can also could replace following code as Operator SDK 0.18.0 based on controller-runtime v0.6.0
```
// TODO Replace with controllerutil.RemoveFinalizer after operator-sdk update (controller-runtime v0.6.0+)
func remove(list []string, s string) []string {
	var slice []string
	for _, v := range list {
		if v != s {
			slice = append(slice, v)
		}
	}
	return slice
}
```

**Comment by rigazilla** [comment]
To minimize the changes, I haven't change the go.mod dependency, I've only updated the `operator-sdk` exe so `make codegen` generates `v1` api.
go code is still based on the old sdk.

**Comment by dmvolod** [comment]
> go code is still based on the old sdk.

Oh, in this case make sense. Thanks
