### ISSUE TITLE
e2e testing failing with "Labels haven't been propagated to pods"

### ISSUE THREAD

**Issue by redmark-ham** [infinispan/infinispan-operator#816]
I'm testing in the 2.0.x branch and noticed the code change for custom labels. What new parameter(s) are need for testing?

Using project "default".
+ cd infinispan-operator
+ export EXPOSE_SERVICE_TYPE=Route
+ EXPOSE_SERVICE_TYPE=Route
+ export KUBECONFIG=/home/fedora/.kube/config
+ KUBECONFIG=/home/fedora/.kube/config
+ export RUN_LOCAL_OPERATOR=false
+ RUN_LOCAL_OPERATOR=false
+ export TESTING_NAMESPACE=datagrid-suite
+ TESTING_NAMESPACE=datagrid-suite
+ oc new-project datagrid-suite
Now using project "datagrid-suite" on server "https://api.test-ocp4-6.qe13.testing:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app ruby~https://github.com/sclorg/ruby-ex.git

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node

+ go mod vendor
+ go clean -testcache ./test/e2e
+ go test -v ./test/e2e -timeout 60m
=== RUN   TestNodeStartup
--- FAIL: TestNodeStartup (71.86s)
panic: Labels haven't been propagated to pods [recovered]
	panic: Labels haven't been propagated to pods

**Comment by dmvolod** [comment]
This expected behavior if operator image doesn't contains last labels propagation code changes.
Please provide operator deployment version

**Comment by Crumby** [comment]
@dmvolod @rigazilla The issue is `TestNodeStartup` test newly assumes that Operator is running locally as it sets env using `os.Setenv`. If you execute the test with the Operator already running within the OpenShift then setting up envs like this doesn't have any effect.

**Comment by redmark-ham** [comment]
I'm testing the 8.1.5 multi arch operator.

selfLink: >-
    /apis/operators.coreos.com/v1alpha1/namespaces/datagrid-suite/clusterserviceversions/datagrid-operator.v8.1.5
  resourceVersion: '1664286'
  name: datagrid-operator.v8.1.5
  uid: 4e21048f-f737-4c53-896d-ef392f870114

**Comment by redmark-ham** [comment]
@rigazilla Will there be new option(s) I need to set before I run the e2e test suite?

**Comment by redmark-ham** [comment]
I've testing with the applied commits in the 2.0.x branch. There is an error so I assume I must be missing some additional configuration steps?

+ go test -v ./test/e2e/main -timeout 60m
=== RUN   TestNodeStartup
--- FAIL: TestNodeStartup (64.83s)
panic: Cannot get the Infinispan operator pod [recovered]
	panic: Cannot get the Infinispan operator pod

**Comment by rigazilla** [comment]
> I've testing with the applied commits in the 2.0.x branch. There is an error so I assume I must be missing some additional configuration steps?
> 
>     * go test -v ./test/e2e/main -timeout 60m
>       === RUN   TestNodeStartup
>       --- FAIL: TestNodeStartup (64.83s)
>       panic: Cannot get the Infinispan operator pod [recovered]
>       panic: Cannot get the Infinispan operator pod

If the operator is deployed in a different namespace you need to set `TESTING_OPERATOR_NAMESPACE` and the user running the testsuite must be allowed to read pods there

**Comment by redmark-ham** [comment]
Thanks let me try it.  Thank you.

**Comment by redmark-ham** [comment]
e2e tests are passing once I hacked the operator pod yaml (name: infinispan-operator-alm-owned ==> name: infinispan-operator)

+ go mod vendor
+ go clean -testcache ./test/e2e/main
+ go test -v ./test/e2e/main -timeout 60m
=== RUN   TestNodeStartup
--- PASS: TestNodeStartup (64.92s)
=== RUN   TestOperatorUpgrade
    main_test.go:221: Operator upgrade stage 'NONE' is unsupported or disabled
--- SKIP: TestOperatorUpgrade (0.00s)
=== RUN   TestClusterFormation
--- PASS: TestClusterFormation (129.97s)
=== RUN   TestClusterFormationWithTLS
--- PASS: TestClusterFormationWithTLS (121.42s)
=== RUN   TestContainerCPUUpdateWithTwoReplicas
--- PASS: TestContainerCPUUpdateWithTwoReplicas (348.17s)
=== RUN   TestContainerMemoryUpdate
--- PASS: TestContainerMemoryUpdate (311.95s)
=== RUN   TestContainerJavaOptsUpdate
--- PASS: TestContainerJavaOptsUpdate (139.09s)
