### ISSUE TITLE
Custom labels missing from zero capacity pods

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#819]
The custom labels introduced by https://github.com/infinispan/infinispan-operator/issues/650 are not applied to the zero capacity pods which are currently used by the Backup/Restore CRs.

**Comment by dmvolod** [comment]
@ryanemerson do we really need labels for such short-lived Pods?

**Comment by ryanemerson** [comment]
Yes. Because even if they're shortlived pods they still contribute to total resource consumption which is important for statistics and billing.

**Comment by dmvolod** [comment]
Thanks, make sense.

**Comment by dmvolod** [comment]
@ryanemerson are you agree that this issue can marked as `good first issue` as it seems to be a simple?
