### ISSUE TITLE
Decouple user and operator endpoints

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#852]
The operator uses the same Infinispan endpoint that is exposed to users in order to perform it's required admin/lifecycle operations. This means that any authentication/authorization settings on this endpoint have to be reflected in the operator code. So far this has been acceptable, as the operator has only allowed credential based authentication, however additional authentication mechanisms such as #851 means that this approach is no longer viable. Therefore, we need to decouple the user and operator admin endpoints.

The two endpoints, "operator" and "user", should each have their own security-realm, so that user configuration does not impact the operator. The operator endpoint would only be exposed via an internal service and it's realm would contain the operator user.

# Endpoints

## Operator
A REST endpoint is exposed on a port other than 11222.

### Credentials
The operator credential is always generated and stored in a dedicated secret per operator instance.

### Metrics
Prometheus only supports BASIC authentication. Either:

1. We allow BASIC auth on the endpoint. In which case we also create a "prometheus" user for this purpose with restricted authorization permissions.
2. We set `metrics-auth=false` so that /metrics can be consumed without authentication

### Encryption
No encryption?
Communication between endpoint and operator/prometheus is always internal within k8s cluster.

## User
The user endpoint works as before, with the exception of credential generation.

### Credentials
If no user credentials are specified, then a "developer" user is generated as before. The "operator" user is no longer contained within this secret. If a user specifies a "operator" user in a secret, then this is treated as a normal user and applied to the user security-realm.

# Image Changes
This requires an additional endpoint to be exposed by the underlying server image along with a dedicated security-realm. Furthermore, an additional identities file will need to be provided for the operator credentials e.g. ADMIN_IDENTITIES_PATH="" & IDENTITIES_PATH="".

**Comment by rigazilla** [comment]
I don't think we need to expose the operator endpoint via internal service since we usually access pods directly

**Comment by dmvolod** [comment]
> I don't think we need to expose the operator endpoint via internal service since we usually access pods directly

Seems to be beginning Batch CR will access Infinispan cluster via service

**Comment by rigazilla** [comment]
Oh, maybe we need it then. I was thinking that a balancer between the operator and pods could split commands on different nodes and cause troubles. We should probably check that we're using the sticky mode.

**Comment by ryanemerson** [comment]
> I don't think we need to expose the operator endpoint via internal service since we usually access pods directly

We need to expose an internal service for the Prometheus ServiceMonitor(s).

**Comment by dmvolod** [comment]
I think we should add this changes implicitly without any impacting on Infinispan CRD structure as we need a new version and migration become complex and complex. For example, admin credentials could be always auto-generated since custom provided will need an additional field in the CRD.
Decoupling admin and user credentials are very desired feature, as user can use SSO, native OCP, etc. in addition to basic methods, but admin should be stable to prevent unexpected behavior such a switching from BASIC to DIGEST auth.
Also we need to determine whether we will allow disabling authentication for admin endpoints or not. It only affects internal communication for Prometheus monitoring and we can skip  this option.

**Comment by dmvolod** [comment]
Also we need to define which interface user or admin we will use for Cache CR as it uses it's own credentials

**Comment by ryanemerson** [comment]
> I think we should add this changes implicitly without any impacting on Infinispan CRD structure as we need a new version and migration become complex and complex. For example, admin credentials could be always auto-generated since custom provided will need an additional field in the CRD.

+1 that's what I'm working on atm. No CRD changes and auto generated admin credentials.

> Also we need to determine whether we will allow disabling authentication for admin endpoints or not. It only affects internal communication for Prometheus monitoring and we can skip this option.

Initially I think authentication should always be enabled.

> Encryption could be disabled, but customers who care about it could use implicit tools such Service Mesh (need to be investigate about operator internal communication securing with mutual TLS setup)

Initially my plan was to have encryption disabled as the operator always uses `--insecure` when executing curl commands against endpoints anyway.

**Comment by ryanemerson** [comment]
> Also we need to define which interface user or admin we will use for Cache CR as it uses it's own credentials

IMO making the user provide a credential secret for the Cache CR does not make sense as in it's current form it will only work for credential based authentication. Furthermore, requiring the user to create and declare the secret is an additional step that we can avoid. If the user is able to create a Cache CR with the configured k8s rbac, then I think that's sufficient. With the admin endpoint we can just use the generated admin credentials for the operator->server auth.

Is there a benefit in allowing users to provide custom user credentials for the Cache CR that I have missed?

**Comment by dmvolod** [comment]
> Is there a benefit in allowing users to provide custom user credentials for the Cache CR that I have missed?

I'm not sure that I could correctly reply, I think @rigazilla know the reason why Cache CR has it's own credentials.

**Comment by dmvolod** [comment]
> IMO making the user provide a credential secret for the Cache CR does not make sense as in it's current form it will only work for credential based authentication. Furthermore, requiring the user to create and declare the secret is an additional step that we can avoid. If the user is able to create a Cache CR with the configured k8s rbac, then I think that's sufficient. With the admin endpoint we can just use the generated admin credentials for the operator->server auth.

+ 1. Yes, totally agreed. In this case it would be nice to introduce new Cache CRD version and set old as deprecated.

**Comment by ryanemerson** [comment]
> In this case it would be nice to introduce new Cache CRD version and set old as deprecated.

Is it worth creating a new CRD version just to remove the `AdminAuth` struct from the Spec?

In the near future there are going to be a lot of changes to the Cache CR, that may require further spec changes. Is it worth simply ingoring the `AdminAuth` values with a logged warning for now and then committing to a new CRD version when more extensive changes are required?

**Comment by dmvolod** [comment]
> > In this case it would be nice to introduce new Cache CRD version and set old as deprecated.
> 
> Is it worth creating a new CRD version just to remove the `AdminAuth` struct from the Spec?
> 
> In the near future there are going to be a lot of changes to the Cache CR, that may require further spec changes. Is it worth simply ingoring the `AdminAuth` values with a logged warning for now and then committing to a new CRD version when more extensive changes are required?

Yes, sure. It's better to wait until we will need fully new structure. We could ignore `AdminAuth` struct, since implementing Batch CR any entity can be created without user access with administrative credentials, but would be nice to identify the individual auth struct nature.
