### ISSUE TITLE
Add Cache CR tests

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#871]
Currently the Cache CR has no automated tests. We should add this to ensure no breaking changes are accidentally merged.

A basic test could entail:

1. Create a Infinispan CR with replica=1 and wait for the cluster to be ready
2. Create a Cache CR that uses the existing DIST_SYNC template
3. Make a rest call to the Infinispan pod to ensure that the cache exists like expected.

Similarly, a second test could be created that does the same as ^, but for stage 2 provides a custom xml config for the cache.

Finally, as the number of Cache CR tests should increase as the CR's capabilities mature, we should create a separate package in `test/e2e` similar to the Batch & Backup/Restore tests.

N.B. examples of how to perform steps 1 & 3 can be found in `test/e2e/main/main_test.go`. Step 2 is similar to create a Infinispan, Backup or Restore CR which there are also examples of in `main_test.go`.

**Comment by dmvolod** [comment]
We have `TestCacheService` in `main_test.go` already which do the same but validates `default` cache only (created on start). It would be nice to utilize and extend this test and don't create a new set of the tests. Also this test uses an external service to interact with the REST API and we need to use that for testing rather than using direct interaction with the Pod as we need to test the customer facing interaction as much as possible.

**Comment by ryanemerson** [comment]
> It would be nice to utilize and extend this test and don't create a new set of the tests.

Imo we need a new set of tests dedicated to the Cache CR as longer term our test coverage is only going to increase. Extending `main_test.go` is ok in the short term, but it does not scale as we keep adding extra functionality. Furthermore, `TestCacheService` will eventually be removed once we drop support for the current CRD version and remove the concept of services.



> Also this test uses an external service to interact with the REST API and we need to use that for testing rather than using direct interaction with the Pod as we need to test the customer facing interaction as much as possible.

+1 to always interacting with the external services.

**Comment by dmvolod** [comment]
> `TestCacheService` will eventually be removed once we drop support for the current CRD version and remove the concept of services.
> 
> >

+1. It's better to remove it once we introduce new Cache CR tests. It can be useful just for native image test and we can keep it until CacheService not deprecated.
