### ISSUE TITLE
`make codegen` should align csv permissions with roles

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#877]

**Comment by rigazilla** [comment]
I've two possible solutions:
1. requires mikefarah yq and jq
2. requires python3 with yaml module

any preference?

**Comment by dmvolod** [comment]
@rigazilla further operator SDK version will support it automatic way, if I'm not wrong
We can try to bit hack and use one version for code generating and keep current one for runtime, but need to validate this way

**Comment by dmvolod** [comment]
If not, i'm prefer to use `yq and jq` but install them in automatic way, like operator SDK
