### ISSUE TITLE
Generate reference CRD

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-operator#953]
Full, commented CRD reference should be generated for each version and included under documentation.

**Comment by ryanemerson** [comment]
Just playing devils advocate, is this really needed? In the Infinispan docs we're moving away from explaining individual configuration attributes in favour of referencing the `*.xsd` files. In this case, I think the generated CRDs are equivalent to XSD.

**Comment by dmvolod** [comment]
> Just playing devils advocate, is this really needed? In the Infinispan docs we're moving away from explaining individual configuration attributes in favour of referencing the `*.xsd` files. In this case, I think the generated CRDs are equivalent to XSD.

@ryanemerson I think @oraNod is talking about well and customer understandable documentation for each field in the golang CRD's code mappings.

**Comment by oraNod** [comment]
Definitely! I think in docs we need an example CRD but I want to get away from manually updating that in the docs. I'd prefer to add comments directly in the golang as @dmvolod mentioned then generate reference like we do with the XSDs in Infinispan docs.

**Comment by oraNod** [comment]
Maybe I didn't explain it well but what you're talking about, @ryanemerson, is how I want to refactor docs. Right now we've got this: https://infinispan.org/docs/infinispan-operator/master/operator.html#ref_datagrid_service_crd-nodes 

Newer users tend to like this reference so they can find descriptions for fields and everything is in one place. We've been cleaning up the yaml directory in docs and removing callouts. The next step I think is to generate the CRs from the code base.

**Comment by ryanemerson** [comment]
Closing as the CRDs are now generated using the go struct annotations.
